### ISSUE TITLE
install error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by buaa3902** [AIM-Harvard/pyradiomics#480]
Package is downloaded from git://github.com/Radiomics/pyradiomics directly. Then following the instruction for Windows:
cd pyradiomics ---------- done
python -m pip install -r requirements.txt ---------- done
python setup.py install ---------- error: Microsoft Visual C++ 14.0 is required
So do I need to install Visual studio 2019?

**Comment by JoostJM** [comment]
Microsoft Visual C++ 14.0 is from Visual Studio 2015, which is needed to compile the C extensions. However, you can also install the C++ compiler separately, and which is available to download for free.

Alternatively, PyRadiomics is pre-compiled for Windows, Linux and Mac and available as on pypi (i.e. you can pip-install pyradiomics).
