### ISSUE TITLE
For Image/Mask geometry mismatch,is it suitable to set geometryTolerance too large？

### ISSUE THREAD

**Issue by cpuxzb** [AIM-Harvard/pyradiomics#507]
For a patient,I get a series of original dicom image.After using the ITK-SNAP software to label the original dicom image,I get one labeled file(file format is nii)(called label.nii).I use the dcmtonii softeare to convert the mass of original dicom image to one nii file(called image.nii).
When I use the 'image.nii' and 'label.nii' to extract radiomic features,I get the following ValueError.
'Image/Mask geometry mismatch. Potential fix: increase tolerance using geometryTolerance, see Documentation:Usage:Customizing the Extraction:Settings:geometryTolerance for more information'
I set the 'geometryTolerance' value to '10' or '100' or '1000'.Only the value is '1000',I get the features.But the default value for 'geometryTolerance' is '1e-16'.
So,what should I do for this?Is the features I get is reliable？

**Comment by fedorov** [comment]
First, you should load .nii files for the image and the mask into a software that is known to recognize spacing/orientation - we recommend [3D Slicer](https://slicer.org).

Once you confirm the label is in the right place, probably the easiest way to handle this situation is to enable resampling - see this entry of the documentation: https://pyradiomics.readthedocs.io/en/latest/faq.html?highlight=resample#geometry-mismatch-between-image-and-mask.

**Comment by aislam388** [comment]
@fedorov Sir, is there any way to use Python resampleMask.py, as mentioned in the bin\resampleMask.py file, from Google Colab? it doesn't work from cmd.

**Comment by aislam388** [comment]
@cpuxzb How were you able to change the value of geometryTolerance?

**Comment by JoostJM** [comment]
@aislam388, When using PyRadiomics from the cmd line, geometery tolerance can be set using `geometryTolerance` setting.

In resamplemask.py this is not an issue. You can use this script from the cmdline as follows:

`python resamplemask.py <image.nrrd> <mask.nrrd> <resampled_mask.nrrd>`, Where the first 2 arguments are the input, and the last the filename to use for storing the resampled mask. Of course, this does require you to have python with the required packages (SimpleITK) installed.

**Comment by yangwei1993** [comment]
i wonder is it right to set the 'geometryTolerance' value to '1000' ?

**Comment by JoostJM** [comment]
@yangwei1993 technically, yes. Though I would not recommend it. Setting this value too large allows for some severe mismatches to be calculated without warning. Better approach would be to investigate why some cases are failing when using a regular value for this setting.
