### ISSUE TITLE
How to process the TCIA data,so that I can use the pyradiomics?

### ISSUE THREAD

**Issue by cpuxzb** [AIM-Harvard/pyradiomics#508]
I downlod the image data form TCIA.
For one patient,the original images are a series of dicom images.The corresponding labeled file is one dicom file.I can use 'dcm2nii' transfer the original file to one file,but I failed to do so on  the labeled file.
What should I do,if I want to analyse the TCIA image data?

**Comment by fedorov** [comment]
What is the modality of the DICOM segmentation file?

You can check that by using [dcmdump](https://support.dcmtk.org/docs/dcmdump.html), and then checking the line that says "Modality". You can find the binary packages of this tool here: https://github.com/QIICR/atom-dicom-dump#install-dcmtk-andor-gdcm (you can also use that package if you want to look at DICOM files more conveniently from Atom editor: https://github.com/QIICR/atom-dicom-dump).
