### ISSUE TITLE
Something is not right with MRI normalization

### ISSUE THREAD

**Issue by hwoodruff** [AIM-Harvard/pyradiomics#511]
We are doing some comparisons between different radiomics SW and came across some troubling results for features extracted before and after normalization (z-score) of MRI volumes (3D ROI breast tumour) . Briefly stated, the only features that should change are stats features since those represent actual voxel values which of course will change. Features derived from matrices (texture, etc) should not change, and for other SW (e.g. OncoRadiomics) this is indeed the case, but as you can see in the file attached it is not for pyradiomics. The only settings that were changed between the two feature extractions was the normalization. Otherwise the images were linearly resampled to isotropic voxels and we're using a fixed number of bins (64).
We want to publish these results, but of course would love to hear your comments on this first.
[_PY_Norm_ResampLin_FixBin64_VS_PY_NoNorm_ResampLin_FixBin64_RG.PDF](https://github.com/Radiomics/pyradiomics/files/3460623/_PY_Norm_ResampLin_FixBin64_VS_PY_NoNorm_ResampLin_FixBin64_RG.PDF)

**Comment by fedorov** [comment]
Thank you for reporting this - we would definitely like to look into this! @JoostJM, the lead developer of pyradiomics, is currently on vacation. We will get back to you after we have a chance to discuss together as a team.

To help us reproduce the issue, can you please answer the following:
* was this issue specific to the dataset you used in your experiments, or it is happening consistently for any dataset?
* were you using the standard pyradiomics command line or you have a custom code? 
 * If the former, can you please share the parameter file you used in the experiments?
 * If the latter, can you please share the custom code?

**Comment by hwoodruff** [comment]
HI,
Below the answers to your questions, and the results of some further investigations:

was this issue specific to the dataset you used in your experiments, or it is happening consistently for any dataset?
For now we only have investigated this problem in our specific dataset

were you using the standard pyradiomics command line or you have a custom code?
We used the standard Pyradiomics script (see attachment). We only changed the settings in de param file (also attachted)


Further investigation showed that the problems have something to do with the resampling method. See the attachment, the comparison of Pyradiomics: normalized vs. not normalized (fixedBin64 and No resampling) shows straight lines, as we would expect. By adding the resampling step, the lines get messed up.

**Comment by fedorov** [comment]
@hwoodruff you did not attach the script you used. 

Now that you clarify the details, I am not sure I agree with you that texture features should not change after resampling. Resampling changes both the image matrix and intensities, and I would actually expect the texture features to change. Can you please explain why you believe the features should remain constant?

I believe this kind of issue is best debugged using a synthetic dataset where you know what the expected answer should be. I am not convinced a patient MR dataset is a good example, especially since it is not public.

**Comment by fedorov** [comment]
@hwoodruff can you follow up on this? I am afraid you attached things to your response by email, and those are discarded by GitHub. You will need to either include links to the files on the web, or attach files directly in the issue, NOT by emailing them.
