### ISSUE TITLE
ValueError: ('Label (%g) not present in mask. Choose from %s', 1, array([2], dtype=uint32))

### ISSUE THREAD

**Issue by fbilly945** [AIM-Harvard/pyradiomics#516]
I‘m new in radiomics and I just encountered this value error:
   ValueError: ('Label (%g) not present in mask. Choose from %s', 1, array([2], dtype=uint32))
How can I fix the problem?

**Comment by JoostJM** [comment]
@fbilly945, This error is precisely what is stated: you selected label 1 as your ROI to extract features. However, in the mask file you supplied, no voxels have the value of "1", i.e. your ROI does not exist. In your mask, only a ROI with label value "2" is present. So if you change the value of the `label` parameter to 2, the extraction should work.

There is a small bug here though, and that is in the formatting of this error. I have fixed this in the latest master (0ff1d8f). The error message is then correctly formatted.

**Comment by raluca-san** [comment]
@fbilly945  try this:
```

settings = {'label': 2}

extractor = radiomics.featureextractor.RadiomicsFeatureExtractor(additionalInfo=True, **settings)
result = extractor.execute(inputImage, mask_resampled)
for key, val in six.iteritems(result):
    print("\t%s: %s" %(key, val))
```

**Comment by nadiaxf** [comment]
Can someone please explain how i can define the value for the label? I have the error which says "choose from [255]. I would like to define --label=255. Where should i write this command? Do i write it immediately after pyradiomics <path/to/img. ,path/to/mask. ? (FYI i am experimenting with a single image single mask.)

**Comment by andreasala98** [comment]
Hi, I'm having te same problem here.
I have a mask with 4 different values and I'm trying to select only one of them.

```
mask_kwargs = {'label': 3}
mask_new = radiomics.imageoperations.getMask(mask, **mask_kwargs)

fof = radiomics.firstorder.RadiomicsFirstOrder(image, mask_new, **settings)
```
and I get the error
```
ValueError: Label (3) not present in mask. Choose from [10 20 30 40]
```

However, when I switch `label`to value 10 (or 20, ...) I get the error
```
  File "/Users/andreasala/Desktop/Tesi/feature-extractor/Script/Features_1order_areas.py", line 123, in <module>
    firstOrderFeatures_1 = radiomics.firstorder.RadiomicsFirstOrder(image, mask_new, **settings_1)
  File "/opt/homebrew/lib/python3.9/site-packages/radiomics/firstorder.py", line 37, in __init__
    self.discretizedImageArray = self._applyBinning(self.imageArray.copy())
  File "/opt/homebrew/lib/python3.9/site-packages/radiomics/base.py", line 117, in _applyBinning
    self.coefficients['Ng'] = int(numpy.max(self.coefficients['grayLevels']))  # max gray level in the ROI
  File "<__array_function__ internals>", line 180, in amax
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2791, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/opt/homebrew/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```


Maybe @JoostJM can have a look into this?
Thanks a lot

**Comment by JoostJM** [comment]
You correctly fixed your first error. The second one occurs a bit later.
Reading your stacktrace, it looks like you implemented the firstorder featureclass directly in your own custom code. My suggestion would be to use the featureextractor module, this is the intended use of PyRadiomics. It applies some checks and provides better diagnostic information to help you track down what is going wrong.

**Comment by achintalapati** [comment]
I am having the same issue as @nadiaxf, where I am trying to run the script in the command line but it does not do anything with the -l argument to update the label. Is there an example with the correct way to do this in order for that argument to be recognized?

**Comment by Georgy415** [comment]
I also experiencing the same problem, anyone please have a solution? 
V_alueError: Label (1) not present in mask. Choose from [255]_

where to add label: 255 , I tried in params.yaml, in command line, --label: 255, -l=255, but nothing is working.
thanks!
