### ISSUE TITLE
Failed to initialize output array for GLCM

### ISSUE THREAD

**Issue by gmisra24** [AIM-Harvard/pyradiomics#525]
I tried to extract GLCM features from a CT series with RTSTRUCT (having multiple ROIs), on executing, I got a warning: "Exception ignored in: 'array_dealloc'
SystemError: <class 'DeprecationWarning'> returned a result with an error set".

Params.yaml (settings):

imageType:
  Original: 
    binWidth: 0.5
  LoG: 
    binWidth: 10
    sigma: [1.0, 2.0, 3.0]
  Wavelet: 
    binWidth: 5

featureClass:

  glcm:
    - 'Autocorrelation'
    - 'JointAverage'
    - 'ClusterProminence'
    - 'ClusterShade'
    - 'ClusterTendency'
    - 'Contrast'
    - 'Correlation'
    - 'DifferenceAverage'
    - 'DifferenceEntropy'
    - 'DifferenceVariance'
    - 'JointEnergy'
    - 'JointEntropy'
    - 'Imc1'
    - 'Imc2'
    - 'Idm'
    - 'Idmn'
    - 'Id'
    - 'Idn'
    - 'InverseVariance'
    - 'MaximumProbability'
    - 'SumEntropy'
    - 'SumSquares'

**Comment by JoostJM** [comment]
The 'error' that is set is probably the deprecation warning, so not really an error, though I don't know which one.
Seeing as you've recieved it as a warning, did the feature extraction run correctly in other aspects?

Just being curious, how did you convert the RTSTRUCT prior to passing it to PyRadiomics?

**Comment by gmisra24** [comment]
thanks for the reply.
with the help of dicom images and RTStruct i have created an image mask, which i have passed to 
PyRadiomics package.

**Comment by JoostJM** [comment]
How did you perform the conversion? did you use plastimatch? 3D slicer?
Can you share the nrrd files you used that caused this error?
