### ISSUE TITLE
When I compute over 6,000 pictures there will be a phenomenon of calculation stagnation

### ISSUE THREAD

**Issue by bigtaotao** [AIM-Harvard/pyradiomics#530]
hello ，I have the same problem，When I compute over 6,000 pictures there will be a phenomenon of calculation stagnation，i use terminal “pyradiomics 32.33_in.csv -j 32 -o out.csv -f csv”and Two days later it got stuck 

**PyRadiomics configuration**
command lines：“pyradiomics 32.33_in.csv -j 32 -o out.csv -f csv”
configruation is  default
**PyRadiomics log file**
it output nothing
**To Reproduce**
pyradiomics 32.33_in.csv -j 32 -o out.csv -f csv

**Expected behavior**
compute and give me result

**Version (please complete the following information):**
 - OS: ubuntu16.04
 - Python version:3.6
 - PyRadiomics version 2.2.0

**Additional context**
my english is poor,Thank you very much for your patience

**Comment by JoostJM** [comment]
@bigtaotao, are all you images same size? otherwise it's possible optimization shifts larger images further back in the queue, making it seem that the calculation slows down, whereas it merely takes longer due to larger input size.

If not, or the difference is too large. How much RAM do you have? Is there a (very) large increase as the extraction runs on (some increase is expected: it retains the calculated values of cases in the RAM)

**Comment by bigtaotao** [comment]
I have 314G memory and I tried giving it CSV with 8 sets of images and using -j 8, it only USES 2 cores and it's still stuck.Almost every image is 300X900

**Comment by bigtaotao** [comment]
i use this to convert png to nrrd and create mask.nrrd
`def make_mask_and_3d(img_path):
    image_3d = img_path.split(".")[0] + "_3d.nrrd"
    image_3d = new_img_root + image_3d[len(img_root):]
    os.makedirs(os.path.split(image_3d)[0],exist_ok=True)
    mask = img_path.split(".")[0] + "_mask.nrrd"
    mask = mask_root + mask[len(img_root):]
    os.makedirs(os.path.split(mask)[0],exist_ok=True)
    # Load the image
    im = sitk.ReadImage(img_path,sitk.sitkUInt8)

    # GetSize() return x, y, z size, array should be z, y, x. use [::-1] to reverse direction
    # True specifies it can use compression

    img_3d = sitk.JoinSeries(im)

    sitk.WriteImage(img_3d,image_3d)

    ma_arr = np.ones(img_3d.GetSize()[::-1], dtype='int')

    # Get the SimpleITK image object from the array
    ma = sitk.GetImageFromArray(ma_arr)

    # Copy geometric information from the image (origin, spacing, direction)
    ma.CopyInformation(img_3d)

    # Store the full mask
    sitk.WriteImage(ma, mask, True) 
`
