### ISSUE TITLE
How to get the features from several labels as a whole

### ISSUE THREAD

**Issue by kevin-why** [AIM-Harvard/pyradiomics#531]
**Describe the bug**
When I use the pyradiomics，I wonder how to merge several labels into one label.(There are 4 labels in my test image, I need to extract the features of them as a whole)

**PyRadiomics configuration**
I used the 【Params.yaml】download from here, I tried to modify the label number in the file.
【label:1→label：1,2.3.4】but unfortunately it doesn't work.

**Version (please complete the following information):**
 - OS: Win10
 - Python version: 3.6
 - PyRadiomics version 2.20

**Comment by JoostJM** [comment]
@kevin-why,

currently, this is not possible if you use PyRadiomics on the command-line. However, in interactive Python it'll be quite easy:

```
import SimpleITK as sitk

from radiomics import featureextractor

ma = sitk.ReadImage(r'path/to/mask.nrrd')
ma_arr = sitk.GetArrrayFromImage(ma)
for l in (2, 3, 4):
  ma_arr[ma_arr == l] = 1

ma_merged = sitk.GetImageFromArray(ma_arr)
ma_merged.CopyInformation(ma)  # geometric information

extractor = featureextractor.RadiomicsFeatureExtractor(r'path/to/params.yaml')
features = extractor.execute(r'path/to/image.nrrd', ma_merged, label=1)  # You can pass in a SimpleITK.Image object directly for image and/or mask

# Features will be a dict with featurename:feature value
```
