### ISSUE TITLE
What's the unit of measurements for major/minor/least axist and volumes?

### ISSUE THREAD

**Issue by rmsandu** [AIM-Harvard/pyradiomics#533]
Sanity check, if you could please help me.

The unit of measurement for axis features is **mm** and for volumes is **ml**?

**Comment by JoostJM** [comment]
Yes and no, all the shape measurements are, in a way, based on the physical coordinates of the volume. As spacing in the volume is expressed in mm, all distances are mm, surface areas are mm^3 and volume is in mm^3 (or **ul**). To transform volume to cm^3 (**ml**), divide by 1000.
