### ISSUE TITLE
can i use one mask for much CT image

### ISSUE THREAD

**Issue by zexllin** [AIM-Harvard/pyradiomics#535]
**Describe the bug**
A clear and concise question regarding your extraction. Please check [FAQ section](https://pyradiomics.readthedocs.io/en/latest/faq.html), PyRadiomics issues and [PyRadiomics Google Groups](https://groups.google.com/forum/#!forum/pyradiomics) to check if your question has been encountered before. If so, but you still require additional help, please reference related issues.

**PyRadiomics configuration**
Add any customization you applied here (i.e. the content of the parameter file used)

**PyRadiomics log file**
If available, add section of the PyRadiomics log related to your question. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**

**Version (please complete the following information):**
 - Python version: [e.g. 3.6]
 - PyRadiomics version [e.g. 2.2.0]

**Additional context**
Add any other context about your question here.

**Comment by fedorov** [comment]
Can you please try to make your question more clear?
