### ISSUE TITLE
[FEAT EXTRACTION] Normalization of dynamic contrast enhancement image

### ISSUE THREAD

**Issue by mangguoxia** [AIM-Harvard/pyradiomics#539]
Hi,

I want to extract gradient features of dynamic contrast enhancement volumes.
The dynamic contrast enhancement images are in 4D, acquired in a certain period of time.
The brightness of the tumor will get higher and higher over time, so the gradient around the tumor edge also get higher and higher over time.

I want to extract the gradient features with different phases(time). 

However, there are images in two types acquired with different scanning parameters in MRI (such as  1.5T and 3T) . The range of gray values of the two types of images is different.
I have to normalize these two different images before extracting the gradient features. 
And i don't want to loss the gradient changing information over time in each type images after the normalizeation.
Do you have any suggestions?
The attachements are the two types of images. 

![1](https://user-images.githubusercontent.com/18598607/68760481-e8b9e700-064c-11ea-9838-ea6a275b774f.png)
![2](https://user-images.githubusercontent.com/18598607/68760484-e9527d80-064c-11ea-92ca-128dc611b166.png)

**Comment by JoostJM** [comment]
@mangguoxia, IMHO, you'd have 2 options:

 1. Normalize a specific timepoint (e.g. timepoint 0) and use the mean and std to scale all other timepoints
 2. Normalize by calculating the mean and std of the volume as a 4D volume (i.e. all timepoints together)

Both approaches would require you to do this outside of the PyRadiomics loop. The easiest would be to make a pre-processing script which does this normalization and the writes out the normalized images, which you can then use in PyRadiomics. Alternatively, you can use PyRadiomics directly in a python script, passing the normalized images as SimpleITK.Image object to the `RadiomicsFeatureExtractor.execute()` method.

**Comment by mangguoxia** [comment]
@JoostJM Thanks for your quickly reply !

Is it feasible to normalize by calculating the mean and std of each timepoint separately? 
I 'm wondering whether this method will loss the gradient changing information over time.

**Comment by JoostJM** [comment]
@mangguoxia,

> Is it feasible to normalize by calculating the mean and std of each timepoint separately?

I suspect that this would indeed lose your gradient changing information over time, as the overall intensity changes due to the wash-in/out of contrast fluid. Normalizing each timepoint separately would remove these overall differences, forcing all into more-or-less the same range.
