### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by raz1** [AIM-Harvard/pyradiomics#541]
I try to install pyradiomics on Anaconda 2019.10/Python 3.7 version using the command: conda install -c radiomics pyradiomics 

I get this error:

_(base) C:\Users\Asher>conda install -c radiomics pyradiomics
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package scikit-learn conflicts for:
pyradiomics -> scikit-learn
Package pywavelets conflicts for:
pyradiomics -> pywavelets[version='>=0.4.0']
Package six conflicts for:
pyradiomics -> six[version='>=1.10.0']
Package trimesh conflicts for:
pyradiomics -> trimesh
Package simpleitk conflicts for:
pyradiomics -> simpleitk!=1.1.0
Package sqlite conflicts for:
python=3.7 -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.1,<4.0a0']
Package numpy conflicts for:
pyradiomics -> numpy[version='>=1.9.2']
Package vs2015_runtime conflicts for:
python=3.7 -> vs2015_runtime[version='>=14.16.27012,<15.0a0']
Package openssl conflicts for:
python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a']
Package pip conflicts for:
python=3.7 -> pip
Package scipy conflicts for:
pyradiomics -> scipy
Package pykwalify conflicts for:
pyradiomics -> pykwalify[version='>=1.6.0']
Package vc conflicts for:
python=3.7 -> vc[version='14.*|>=14,<15.0a0|>=14.1,<15.0a0']
pyradiomics -> vc=9_

How can I solve it?

Thanks a lot.

**Comment by JoostJM** [comment]
First try to install it in a separate (new) environment.
This error basically tells you that there are discrepancies between installed and required version of some packages PyRadiomics depends on

**Comment by JoostJM** [comment]
Alternatively, you can force updating the dependencies by specifying `--all`.

For more tips and tricks, see the conda install [documentation](https://docs.conda.io/projects/conda/en/latest/commands/install.html)

**Comment by raz1** [comment]
I perfromed:
conda update  --all and updated all.
later
conda install -c radiomics pyradiomics

Still problems:
(base) C:\Users\Asher>conda install -c radiomics pyradiomics
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abor/
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package six conflicts for:
pyradiomics -> six[version='>=1.10.0']
Package simpleitk conflicts for:
pyradiomics -> simpleitk!=1.1.0
Package pywavelets conflicts for:
pyradiomics -> pywavelets[version='>=0.4.0']
Package vc conflicts for:
pyradiomics -> vc=9
python=3.7 -> vc[version='14.*|>=14,<15.0a0|>=14.1,<15.0a0']
Package pip conflicts for:
python=3.7 -> pip
Package openssl conflicts for:
python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a']
Package sqlite conflicts for:
python=3.7 -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.1,<4.0a0']
Package pykwalify conflicts for:
pyradiomics -> pykwalify[version='>=1.6.0']
Package scipy conflicts for:
pyradiomics -> scipy
Package scikit-learn conflicts for:
pyradiomics -> scikit-learn
Package vs2015_runtime conflicts for:
python=3.7 -> vs2015_runtime[version='>=14.16.27012,<15.0a0']
Package numpy conflicts for:
pyradiomics -> numpy[version='>=1.9.2']
Package trimesh conflicts for:
pyradiomics -> trimesh


Any other ideas?

**Comment by fedorov** [comment]
I don't use conda, but what I would try is create a virtual environment and try install pyradiomics there. This article looks like a good start: https://towardsdatascience.com/a-guide-to-conda-environments-bc6180fc533.

**Comment by ctwangtz** [comment]
> I perfromed:
> conda update --all and updated all.
> later
> conda install -c radiomics pyradiomics
> 
> Still problems:
> (base) C:\Users\Asher>conda install -c radiomics pyradiomics
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: |
> Found conflicts! Looking for incompatible packages.
> This can take several minutes. Press CTRL-C to abor/
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Package six conflicts for:
> pyradiomics -> six[version='>=1.10.0']
> Package simpleitk conflicts for:
> pyradiomics -> simpleitk!=1.1.0
> Package pywavelets conflicts for:
> pyradiomics -> pywavelets[version='>=0.4.0']
> Package vc conflicts for:
> pyradiomics -> vc=9
> python=3.7 -> vc[version='14.*|>=14,<15.0a0|>=14.1,<15.0a0']
> Package pip conflicts for:
> python=3.7 -> pip
> Package openssl conflicts for:
> python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a']
> Package sqlite conflicts for:
> python=3.7 -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.1,<4.0a0']
> Package pykwalify conflicts for:
> pyradiomics -> pykwalify[version='>=1.6.0']
> Package scipy conflicts for:
> pyradiomics -> scipy
> Package scikit-learn conflicts for:
> pyradiomics -> scikit-learn
> Package vs2015_runtime conflicts for:
> python=3.7 -> vs2015_runtime[version='>=14.16.27012,<15.0a0']
> Package numpy conflicts for:
> pyradiomics -> numpy[version='>=1.9.2']
> Package trimesh conflicts for:
> pyradiomics -> trimesh
> 
> Any other ideas?

If you are Chinese, maybe I can tell you how to solve it using QQ.
