### ISSUE TITLE
Implement the geometric mean in first order features

### ISSUE THREAD

**Issue by GiulioBen** [AIM-Harvard/pyradiomics#556]
The question is simple:

I want to calculate the average ADC inside the VOI. 

It can be calculated by using the average of the ADC map inside the VOI (e.g. computed from the b0 and b800 images, but I don't have it)

or

by using the formula ADC_VOI = -ln(m_800/m0)/800 where m is the **geometric** mean of the voxels inside the VOI (simply, the log transform the average in the geometric mean).

Why not to implemet it?

Thank you.

GB

**Comment by fedorov** [comment]
@GiulioBen I am confused by your question. Are you asking about adding geometric mean OR are you asking to solve a specific problem calculating ADC for your input? I don't understand the formula ADC_VOI = -ln(m_800/m0)/800. But you can apply arithmetic operations and transformations to your image using SimpleITK before passing the image to pyradiomics for feature extraction: https://simpleitk-prototype.readthedocs.io/en/latest/user_guide/plot_image.html#image-operations.

**Comment by GiulioBen** [comment]
Thank you for the prompt reply.

At the moment I'm using the batch command-line pyradiomics, therefore I'm just feeding the images+masks without processing them beforehand.

I have some DWI images, my idea was to use the geometric mean to compute the ADC.
Maybe I'm mistaking but using the log properties and the definition of ADC I obtain:
![CodeCogsEqn (1)](https://user-images.githubusercontent.com/38356385/73644457-baf5a480-4675-11ea-8e42-69e4bc4a3eb7.gif)

Where is the issue of using the geometric mean inside the VOI? 
Thank you, regards.
