### ISSUE TITLE
Feature extraction from 2D image

### ISSUE THREAD

**Issue by hellorp1990** [AIM-Harvard/pyradiomics#619]
Hi,
I am working with 2D images currently. I can use pyradiomics to generate features. But I have one issue or doubt.
My images are in .png format (8bit grayscale). So when I use these 2d images directly, I can have a set of radiomics features. 

In some older issues in pyradiomics, I found the moderator was asking to use  sitk.joinseries () for 2d images. So I used that and the code is running and generates features as well. 
But the problem is the features obtained from direct 2d images and after joinseries() are not same. I understood that it may not be same. But my question is which one is the correct way or calculating features, as I will have different results using two different method.

**Comment by JoostJM** [comment]
Which features are different?

There should be no difference in features. The only special case is shape, for which there is a 3D en 2D equivalent.

In those older issues, joinseries was required, as PyRadiomics did not yet support 2D input, which is not an issue anymore.

**Comment by rcuocolo** [comment]
I can confirm that since 2D extraction has been officially supported I have found no issues extracting features from truly 2D png image files (exported from an ultrasound scanner).

**Comment by dzerkes** [comment]
What is the code to extract features on a 2d grayscale image (.png for example) without inputting also an inputMask too? I would like to extract some GLCM, GLSZM features but it is asking for inputMask too.
