### ISSUE TITLE
[FEAT EXTRACTION] from 2D figure

### ISSUE THREAD

**Issue by reagan55** [AIM-Harvard/pyradiomics#659]
Dear sir,
I try to extract the features from the 2D figure(the figure affilated
[Desktop.zip](https://github.com/Radiomics/pyradiomics/files/5548450/Desktop.zip)
), but return the following errors:

RuntimeError: Exception thrown in SimpleITK ReadImage: D:\a\1\sitk-build\ITK\Modules\IO\NRRD\src\itkNrrdImageIO.cxx:252:
itk::ERROR: NrrdImageIO(0000028C591DF7D0): ReadImageInformation: Error reading G:\sarcopenia_wyc\plain16nrrd_single\CT1284712/2 .nrrd:
[nrrd] nrrdLoad: trouble reading "G:\sarcopenia_wyc\plain16nrrd_single\CT1284712/2 .nrrd"
[nrrd] nrrdRead: trouble
[nrrd] _nrrdRead: trouble reading NRRD file
[nrrd] _nrrdFormatNRRD_read: trouble parsing space directions info |(0.736328125,0,0) (0,0.736328125,0) (0,0,5)|
[nrrd] _nrrdReadNrrdParse_space_directions: seem to have more than expected 2 directions

A clear and concise question regarding your extraction. Please check [FAQ section](https://pyradiomics.readthedocs.io/en/latest/faq.html), PyRadiomics issues and [PyRadiomics Slicer Discourse](https://discourse.slicer.org/c/community/radiomics/23) to check if your question has been encountered before. If so, but you still require additional help, please reference related issues.

**PyRadiomics configuration**
Add any customization you applied here (i.e. the content of the parameter file used)

**PyRadiomics log file**
If available, add section of the PyRadiomics log related to your question. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**

**Version (please complete the following information):**
 - wind10
 - Python version: 3.7
 - PyRadiomics version:3.0.1

**Additional context**
Add any other context about your question here.

**Comment by JoostJM** [comment]
@reagan55, How did you create this nrrd file? The data is of shape (512, 512), i.e. 2D, but the metadata indicates a 3D volume. SimpleITK throws an error because of this.

**Comment by reagan55** [comment]
@JoostJM I used 3D slicer to created the NRRD file。

**Comment by JoostJM** [comment]
Can you describe your specific process for creating the files using 3D slicer, as this is most certainly a bug (in creating those files). If possible, also start an issue on the slicer forum (discourse.slicer.org), to better be able to learn what caused the bug and how to correct it.

**Comment by JoostJM** [comment]
Stale issue, closing...
