### ISSUE TITLE
[FEAT EXTRACTION]

### ISSUE THREAD

**Issue by esrasmr** [AIM-Harvard/pyradiomics#661]
Hello, 
I have nearly 100 MR images of brain tumors and I'm extracting Radiomics in batch processing manner. There is a very large difference in in-plane spacing and slice thickness in the dataset. I tried to extract features without resampling (Example no resampling setting file) but it failed to extract features in most of the images. 
Slice thickness varies from 0.8 to 6.5 and also in-plane spacing changes as well. My question is  should I resample the data according to the smallest slice thickness and highest in-plane resolution? Is that a proper approach in that situation?
Thank you.

**Comment by JoostJM** [comment]
My suggestion would be to compromise. Resampling all to the lowest resolution interpolates quite a lot for the images with larger slice thickness, while resampling all to the largest slice thickes removes a lot of usefull information. Try something lik [2, 2, 2]  or [ 3, 3, 3].

**Comment by fedorov** [comment]
I am wondering if too much detail will be lost going from 0.8 to 2 or 3 in-plane. I would look at how this was done in similar studies. Here's one study to consider perhaps: https://pubs.rsna.org/doi/full/10.1148/radiol.2018180946.

**Comment by esrasmr** [comment]
Thank you, I will look at this.
