### ISSUE TITLE
[FEAT EXTRACTION]

### ISSUE THREAD

**Issue by niclas-b** [AIM-Harvard/pyradiomics#662]
**Describe the bug**
If I try to execute feature extraction from my 2D bmp grayscale images, I get the following Error message:
`sitk::ERROR: Pixel type: vector of 8-bit unsigned integer is not supported in 2D`

**To Reproduce**
```
from radiomics import featureextractor
from radiomics import logging
import radiomics
extractor = featureextractor.RadiomicsFeatureExtractor(distances  = [1, 2, 5, 10], label = 255)
extractor.disableAllFeatures()
extractor.enableFeatureClassByName('glcm')
radiomics_features.append(extractor.execute(img, mask))
```

**Log-File output:**
```
INFO:radiomics.featureextractor: Calculating features with label: 255
INFO:radiomics.featureextractor: Loading image and mask
INFO:radiomics.imageoperations: Extracting mask at index 0
```

**Speicfications**
 - OS: 8.04.5 LTS (Bionic Beaver)
 - Python version: 3.7.7
 - PyRadiomics version 3.0.1

Regards,
Niclas

**Comment by JoostJM** [comment]
While your input may seem to be grayscale, BMP images are most often not. This is also what is detailed by the error, as you bmp is a *vector* of 8-bit float. In your case, you can simply select a certain color channel and extract features. That said, what kind of imaging is you input? BMP images do not contain any geometric information. If your images are obtained by converting DICOM, I'd strongly advise re-converting them to e.g. nrrd of niftii image formats. In addition to having truly grayscale datatypes where possible, it also contains important geometric information like pixel spacing and direction cosines.

**Comment by niclas-b** [comment]
Thanks a lot for the answer. I simply forgot the images have color channels indeed because of usually loading them in grayscale mode.
I got these scanning electron microscope files of textile fibres as part of my thesis. I appreciate your suggestion and will ask my supervisor about the original data type and what information could have gone lost.
Best Regards,
Niclas Bilitewski

**Comment by zh-zhang1984** [comment]
I also encounter the same error reporting, Do you know how to convert a PNG multiple channel image to grey scale?
