### ISSUE TITLE
[FEAT EXTRACTION] Wonder how features are caculated for mask with multi ROIs

### ISSUE THREAD

**Issue by srkeyan** [AIM-Harvard/pyradiomics#664]
When handing a mask with multi spatially separated ROIs, only one set of features are outputed
ALL background pixels have value=0 and all ROI pixels have value=1

But I still need to know the process, whether :
1. All ROIs are considered as one, and caculated features?
2. Features are caculated independently with each ROI, and then merged as one under some certain rules? if This is the case, where can I check the rules?

Thanks

**Comment by srkeyan** [comment]
@JoostJM Sir, would be grateful if you can check this for me

**Comment by jvanlunenburg** [comment]
as I recall the mask is a uint8 type, so each roi can have a different integer, regardless of spatial continuity. You could have up to 255 rois in a single "mask" structure.

The fact that you are using a single non-contigous roi shouldn't affect non-shape feature calculations?

**Comment by srkeyan** [comment]
> as I recall the mask is a uint8 type, so each roi can have a different integer, regardless of spatial continuity. You could have up to 255 rois in a single "mask" structure.
> 
> The fact that you are using a single non-contigous roi shouldn't affect non-shape feature calculations?

I was asking how features are caculated when there are multiple speatate rois

**Comment by jvanlunenburg** [comment]
> > as I recall the mask is a uint8 type, so each roi can have a different integer, regardless of spatial continuity. You could have up to 255 rois in a single "mask" structure.
> > The fact that you are using a single non-contigous roi shouldn't affect non-shape feature calculations?
> 
> I was asking how features are caculated when there are multiple speatate rois

If all roi values are equal to 1, then by definition you have a *single* roi, regardless of their spatial continuity.

**Comment by srkeyan** [comment]
> > > as I recall the mask is a uint8 type, so each roi can have a different integer, regardless of spatial continuity. You could have up to 255 rois in a single "mask" structure.
> > > The fact that you are using a single non-contigous roi shouldn't affect non-shape feature calculations?
> > 
> > 
> > I was asking how features are caculated when there are multiple speatate rois
> 
> If all roi values are equal to 1, then by definition you have a _single_ roi, regardless of their spatial continuity.

So, if there are two ROIs with diameter 1, and they have distance 10, then I will get feature which say the diameter is 12?

**Comment by jvanlunenburg** [comment]
> > > > as I recall the mask is a uint8 type, so each roi can have a different integer, regardless of spatial continuity. You could have up to 255 rois in a single "mask" structure.
> > > > The fact that you are using a single non-contigous roi shouldn't affect non-shape feature calculations?
> > > 
> > > 
> > > I was asking how features are caculated when there are multiple speatate rois
> > 
> > 
> > If all roi values are equal to 1, then by definition you have a _single_ roi, regardless of their spatial continuity.
> 
> So, if there are two ROIs with diameter 1, and they have distance 10, then I will get feature which say the diameter is 12?

Features belonging to the Shape category may lose interpretability with a non-contigous roi. So you may get 12, or NaN, or something else. Depends on the formula implementation.

**Comment by JoostJM** [comment]
> So, if there are two ROIs with diameter 1, and they have distance 10, then I will get feature which say the diameter is 12?

This is what indeed happens, though I agree with @jvanlunenburg that shape features may lose interpretability with non-contiguous ROI.

PyRadiomics can calculate features for ROIs separately (either with differntly valued pixels in the mask, see parameter `label`, or with a vector pixel type, with each ROI occupying a certain index (allows overlapping ROIs, see parameter `label-channel`

In your case, I'd advise using SimpleITK's  ConnectedComponentImageFilter, which assigns a unique value to each connected component (i.e. individual, contiguous ROI) in your mask. Examples to achieve this have been detailed in these issues.

**Comment by srkeyan** [comment]
> > So, if there are two ROIs with diameter 1, and they have distance 10, then I will get feature which say the diameter is 12?
> 
> This is what indeed happens, though I agree with @jvanlunenburg that shape features may lose interpretability with non-contiguous ROI.
> 
> PyRadiomics can calculate features for ROIs separately (either with differntly valued pixels in the mask, see parameter `label`, or with a vector pixel type, with each ROI occupying a certain index (allows overlapping ROIs, see parameter `label-channel`
> 
> In your case, I'd advise using SimpleITK's ConnectedComponentImageFilter, which assigns a unique value to each connected component (i.e. individual, contiguous ROI) in your mask. Examples to achieve this have been detailed in these issues.

Thanks.
If i use SimpleITK's ConnectedComponentImageFilter, then I will get several set of features each describing one roi ? or I juse get one set of features?

**Comment by JoostJM** [comment]
This gives you back a mask, with each ROI given it's own unique label. To extract features for each ROI, run PyRadiomics multiple times, using the same mask and image, but specifying the different labels.

This can also be accomplished in batch mode, where you add an additional column with header "Label", specifying the different labels with the same image/mask combination (i.e. each combination of image, mask and label is 1 row in your CSV file).

**Comment by sneh-debug** [comment]
@JoostJM i tried  this way for Wavelet input image and the Extraction parameters were:
         {'minimumROIDimensions': 2, 'minimumROISize': None, 'normalize': False, 'normalizeScale': 1, 'removeOutliers': None, 'resampledPixelSpacing': None, 'interpolator': 3, 'preCrop': False, 'padDistance': 5, 'distances': [1], 'force2D': False, 'force2Ddimension': 0, 'resegmentRange': None, 'label': 1, 'additionalInfo': True, 'binWidth': 25, 'sigma': [2], 'verbose': True}
Enabled input images:
        Wavelet
Enabled features:
         {'firstorder': [], 'glcm': [], 'gldm': [], 'glrlm': [], 'glszm': [], 'ngtdm': [], 'shape': []} and the code used is:

`
            image = sitk.ReadImage(imageName) #input image
            stats=sitk.ConnectedComponentImageFilter()
            #stats = sitk.LabelShapeStatisticsImageFilter()
            mask = mask = sitk.ReadImage(maskName) #ground truth segmentation
            stats.Execute(mask)

            glcmFeatures = glcm.RadiomicsGLCM(image, mask, **settings)
            glcmFeatures.enableAllFeatures()

            for f in glcmFeatures.enabledFeatures.keys():
                print('  ', f)
                print(getattr(glcmFeatures, 'get%sFeatureValue' % f).__doc__)

            print('Will calculate the following GLCM features: ')
            resultsglcm = glcmFeatures.execute()`
I found no changes in feature extracted using Original Image operation or LOG filter operation, am i making some mistake?

**Comment by JoostJM** [comment]
see #677
