### ISSUE TITLE
Run script on multiple cores

### ISSUE THREAD

**Issue by dzerkes** [AIM-Harvard/pyradiomics#665]
Hi, I'm having many patients to extract features. But pyradiomics uses only 1 core and its very slow maybe it takes 26 hours for 90 patients. Is there any way to run it using multiple cores? I tried using -j flag on python script but did not work. 

Thanks in advance.

**Comment by JoostJM** [comment]
@dzerkes, What do you mean by using the `-j` flag on the python script? This flag is a commandline argument that should be used with the PyRadiomics cmdline entry point (either by directly running PyRadiomics from the commandline or through the `PyRadiomicsCommandLine` class, which you can initialize using your own custom arguments)

If used there, the `-j` flag should work just fine.

**Comment by JoostJM** [comment]
If you successfully configured the use of multiple cores, you should get a log message along the line of: 

`Input valid, starting parallel extraction from <num_cases> cases with <num_cores_used> workers...`

If only one core is used (default), the message reads

`Input valid, starting sequential extraction from <num_cases> cases...`

**Comment by dzerkes** [comment]
> If you successfully configured the use of multiple cores, you should get a log message along the line of:
> 
> `Input valid, starting parallel extraction from <num_cases> cases with <num_cores_used> workers...`
> 
> If only one core is used (default), the message reads
> 
> `Input valid, starting sequential extraction from <num_cases> cases...`

Ok I understand what you mean. Actually, At this point I am using multiprocessing module of python and and split the dataset into batches that will run parallel in my cores. I think pyradiomics cmdline will make the work I want more complex since there is plenty of stuff in my python script. After it finishes, I'll see if it worked as expected. Thanks for your response.

**Comment by JoostJM** [comment]
Internally, PyRadiomics also uses the `multiprocessing` to run in parallel, where the parelellization is done on a per-case basis, and the number of workers controls the size of the process-pool processing the cases.

**Comment by JoostJM** [comment]
Interesting to know, I made the processing in the `featureextractor` module thread-safe and can be pickled, so if you have 1 feature extractor instantiated (with all of the customization loaded), you can forward it to your other workers as well.

**Comment by dzerkes** [comment]
> Interesting to know, I made the processing in the `featureextractor` module thread-safe and can be pickled, so if you have 1 feature extractor instantiated (with all of the customization loaded), you can forward it to your other workers as well.

That's great. The structure I'm using for multiprocessing is the following by the way:

`
def process(filename):
      featureVector -> extractor(filename/ct,filename/mask)
      return featureVector

files = [...list of filenames]
pool = Pool(processes=16)
results = pool.map(process, files)
`
So I let pool.map split the dataset into chunks by default and return every dictionary into results. In the end I'll just loop over results and combine the dictionaries.

**Comment by JoostJM** [comment]
@dzerkes, basically identical to what PyRadiomics does internally. See [this](https://github.com/AIM-Harvard/pyradiomics/blob/master/radiomics/scripts/__init__.py#L242-L261) part of the code for details. Biggest difference is that PyRadiomics functionality can be cancelled by a CTRL+C event, and that the processing functions are a bit more complex to allow for the different usecases.

**Comment by JoostJM** [comment]
Part of the added complexity is setting up logging in a non-conflicting way.

**Comment by dzerkes** [comment]
I was trying running with python's multiprocessing but unfortunately everytime my CPU reduces to 0% and I cant understand why. Only in one CT I got an error that there is a size mismatch between the scans and thats why 1 core stopped. But the others stop without warning. Do you know what this can be? Maybe I try without my python program and execute it by CMD.

**Comment by Ravi-shankar100** [comment]
Hi @dzerkes 
Were you able to do multiprocessing using python scripts itself ?
Even I am facing the same issue unable to extract features through parallel processing.
Please help me if you had already solved this.

**Comment by dzerkes** [comment]
> Hi @dzerkes
> Were you able to do multiprocessing using python scripts itself ?
> Even I am facing the same issue unable to extract features through parallel processing.
> Please help me if you had already solved this.

Yes I used multiprocessing framework of python. Just split the dataset into batches and run them in parallel (as much as the cores of your cpu)
