### ISSUE TITLE
[FEAT EXTRACTION] Why are firstorder features influenced by gray level discretization?

### ISSUE THREAD

**Issue by GiulioBen** [AIM-Harvard/pyradiomics#666]
I changed the discretization between several values of binWidth (bw) and binCount (bc) and built a model with the radiomic features. I expected the model was the same, but it was not (I set the seed correctly)

I report below a table with some of the different configurations:

```
disc	filter			features	AUC
bw8	original+lbp+wavelet	firstorder  0.7515625  
bc128	original+lbp+wavelet	firstorder  0.7187500  
bc64	original+lbp+wavelet	firstorder  0.7171875  
bw32	original+lbp+wavelet	firstorder  0.7421875 
bc16	original+lbp+wavelet	firstorder  0.7140625 
bw16	original+lbp+wavelet	firstorder  0.7421875  
bw4	original+lbp+wavelet	firstorder  0.7406250  
bc256	original+lbp+wavelet	firstorder  0.7078125  
bc32	original+lbp+wavelet	firstorder  0.7218750  
bc8	original+lbp+wavelet	firstorder  0.7093750  
bw128	original+lbp+wavelet	firstorder  0.7390625  
bw64	original+lbp+wavelet	firstorder  0.7281250  
bw256	original+lbp+wavelet	firstorder  0.7171875  
```

In the documentation I find that firstorder features are not influenced by discretization, and I can't find any mention of the fact that filters are influenced by the discretization too (they should be applied on the inizial image).

Can someone explain what I'm missing?

Thank you!

**Comment by JoostJM** [comment]
Both firstorder Uniformity and Entropy are affected by discretization, this is also detailed in the documentation.
