### ISSUE TITLE
DICOM To nrrd

### ISSUE THREAD

**Issue by DevHicham** [AIM-Harvard/pyradiomics#667]
Hello,
i convert my dicom serie to nrrd using plastimatch convert  . i get my output but i don't know how can i get the mask?! i work with this dataset https://wiki.cancerimagingarchive.net/display/Public/CT+COLONOGRAPHY#35392130d1cefb9aa094f3eba40bb141de0229b 
I used this command :
plastimatch convert --input plastimatch\1.3.6.1.4.1.9328.50.4.0001 --output-img outfile.nrrd --output-type float
thank u !!

**Comment by fedorov** [comment]
Unfortunately, that collection does not provide any masks for the regions of interest, and the annotation of lesions is in a non-standard format. You will need to look at the accompanying XML files that seem to provide locations of lesions. I have not tried to interpret those XML files myself - would be great to hear about your experience.

**Comment by DevHicham** [comment]
> Unfortunately, that collection does not provide any masks for the regions of interest, and the annotation of lesions is in a non-standard format. You will need to look at the accompanying XML files that seem to provide locations of lesions. I have not tried to interpret those XML files myself - would be great to hear about your experience.

ok thank you :)

**Comment by DevHicham** [comment]
I found your explanations about converting DICOM series to nrrd files here :
https://discourse.slicer.org/t/how-can-i-convert-dicom-series-to-nrrd-files-in-batch-mode/3421/11 
, can it help me solve my problem (get the ROI of all my dicom series  ) ??
 if yes how?! and thank you very much.
