### ISSUE TITLE
it seems something wrong in the documentation

### ISSUE THREAD

**Issue by ROOKLO** [AIM-Harvard/pyradiomics#668]
in the documentation of NGTDM, s2 should be |2-15/5|+|2-9/3|=2,  am I right?

**Comment by JoostJM** [comment]
Correct, though this has already been fixed in #639. It appears that the docs are not updated at the moment, possibly due to the recent transition of the PyRadiomics organization from Radiomics to AIM-Harvard.

**Comment by fedorov** [comment]
> possibly due to the recent transition of the PyRadiomics organization from Radiomics to AIM-Harvard

That's a good point, I didn't think about that when we discussed transition with Hugo. ReadTheDocs should probably be reconfigured to point to the new location.
