### ISSUE TITLE
change HU values for feature extraction

### ISSUE THREAD

**Issue by hellorp1990** [AIM-Harvard/pyradiomics#669]
Hello All,

I have a question regarding feature extraction and HU values. 

In 3D slicer, when I was using the head and neck CT data, the brightness/contrast (window width/level) [HU values] can be changed to highlight bones or soft tissues. I believe in 3D slicer bone settings for HU value is default (I can change to manual HU value range) for visualization. 

Now when I use the CT data for pyradiomics how does the brightness/contrast (window width/level) [HU values] works? Whats the default  HU value range or can I specify a manual HU range for pyradiomics? 

 I was wondering as, if I use bone settings or soft tissue settings the radiomics feature value will be changed.

Thank you

**Comment by pieper** [comment]
Hi - the window/level setting in Slicer are for display only and don't impact the underlying HU values.  You can confirm this by looking at the DataProbe in the lower left as you mouse over the images.  Those values will be used by radiomics.

**Comment by ChanAndy** [comment]
As long as you ensure that the Hu range is larger than the pixel range in your mask area, the feature extraction will not be affected
