### ISSUE TITLE
[FEAT EXTRACTION]

### ISSUE THREAD

**Issue by daivagyapareek** [AIM-Harvard/pyradiomics#670]
**Describe the bug**
Kernel is dying when running extractor.execute() command

**PyRadiomics configuration**
No Customization

**PyRadiomics log file**
Log file is attached

**To Reproduce**
Running below commands and immediately my kernel is dies after running extractor.execute(). Attached zip contains jupyter notebook that i am running.

import os
import SimpleITK as sitk
import radiomics
from radiomics import featureextractor

params = {}
params['binwidth'] = 20
params['sigma'] = [1,2,3]
params['verbose'] = True

extractor = featureextractor.RadiomicsFeatureExtractor(**params)

pathOrig = os.path.join(os.getcwd(), "radiomic_data/brain1_image.nrrd")
pathlabel = os.path.join(os.getcwd(), "radiomic_data/brain1_label.nrrd")

result = extractor.execute(pathOrig,pathlabel)

**Version (please complete the following information):**
 - OS: MaxOS BigSur 11.1 (32 GB MacBook Pro (15 inches) 2018 Model)
 - Python version: 3.7.4
 - PyRadiomics version: 3.0.1

[Archive.zip](https://github.com/AIM-Harvard/pyradiomics/files/5756305/Archive.zip)

**To Reproduce**
I have just installed the Pyradiomics using "pip install pyradiomics --ignore-installed". I got this error though when installed "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
astroid 2.3.1 requires typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8", which is not installed.
astroid 2.3.1 requires six==1.12, but you have six 1.15.0 which is incompatible."
Also, when i was trying to install using "pip install pyradiomics" i got following error "ERROR: Cannot uninstall 'ruamel-yaml'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

**Comment by JoostJM** [comment]
Why do you specify `--ignore-installed`?
The error you are describing seems to me like you receiving errors during installation of PyRadiomics, which, following the error description, stems from you forcing pip to ignore installed packages.

The error about ruamel-yaml I do not fully understand, You could try to manually install PyYaml and PyKwalify, those are the only packages using yaml, and are in turn used by PyRadiomics to parse the configuration file.
