### ISSUE TITLE
Feature extraction for 2d image

### ISSUE THREAD

**Issue by gayathri199612** [AIM-Harvard/pyradiomics#671]
Hi,
I want to extract features from the segmented thermal image. I have separated my thermal foot image from the background by making the background pixels as zero. The binary mask for the same is created which is in the format of n x n. The dimension of the image and mask are same. Both the images are loaded with the sitkint8 to the extractor. The label defined is 255.
The issue is that after the features are extracted from the image and mask certain first order features like minimum, percentile, mean, median are represented as negative values. So how is it possible to get these values as negative from the image intensities.
I have attached my images here.

please do the needful

Thank in advance!

![D605_L](https://user-images.githubusercontent.com/60851459/103759621-08bf1d80-503a-11eb-804d-b193321737f3.jpeg)
![D605_L_mask](https://user-images.githubusercontent.com/60851459/103759642-12e11c00-503a-11eb-837e-85d3f2661c9c.png)

**Comment by JoostJM** [comment]
sitkint8 has range [-127 to 128]. Is it possible you meant to load them using sitkuint8 [0, 255]?
