### ISSUE TITLE
[FEAT EXTRACTION] 2D image feature extraction

### ISSUE THREAD

**Issue by Usernamechecksin** [AIM-Harvard/pyradiomics#675]
Hello,

I am just starting out using pyradiomics and am working with 2D image for which I would like to extract features from the whole image. The image is a .tiff file and the mask will be of the whole image. I am generating the mask using 

```
import SimpleITK as sitk
import numpy as np

im = sitk.ReadImage('path/to/image.nrrd')
ma_arr = np.ones(im.GetSize()[::-1])  # reverse the order as image is xyz, array is zyx
ma = sitk.GetImageFromArray(ma_arr)
ma.CopyInformation(im)  # Copy geometric info

from radiomics.featureextractor import RadiomicsFeatureExtractor

extractor = RadiomicsFeatureExtractor('path/to/params.yml')
features = extractor.execute(im, ma)
```
as written by @JoostJM  in a previous post. I was wondering how I could batch input the images and save the masks? Do I necessarily need a .csv file in this situation?
I found some source code online and this is my attempt. Have not coded prior please mind my efforts.

```
import SimpleITK as sitk
import numpy as np
import os
from PIL import Image

path = r"C:\Users\X\Documents\testimages"

# Loop through all provided arguments
for filename in os.listdir(path):
    if "." not in filename:
        continue
    ending = filename.split(".")[1]
    if ending not in ["tif"]:
        continue

    try:
# Attempt to open an image file
        #image = Image.open(os.path.join(path, filename))
    except IOError as e:
# Report error, and then skip to the next argument
        print ("Problem opening", filepath, ":", e)
        continue

# Perform operations on the image here
    im = sitk.ReadImage(image)
    ma_arr = np.ones(im.GetSize()[::-1])  # reverse the order as image is xyz, array is zyx
    ma = sitk.GetImageFromArray(ma_arr)
# ma.CopyInformation(im)  # Copy geometric info

# Split our origional filename into name and extension
    name, extension = os.path.splitext(filename)

# Save the image
   
    save_path = os.path.join(r"C:\Users\X\Documents\testimages",name +'_mask.tif')
    sitk.WriteImage(ma,save_path) 
    print(name + '_mask.tif')
    

```
I continue to get an error itk:ERROR: TIFFImageIO(): TIFF supports unsigned/signed char, unsigned/signed short, and float

I figured after this I would just put the path into the excel document. Nothing in the label column I assume.

 - OS: Windows Version 1909
 - Python version: 3.7.9
 - PyRadiomics version: 3.0

Thank you for your help.

**Comment by JoostJM** [comment]
The error is related to the use of TIFF as output format, it does not support integer as a datatype (which is the default for `np.ones` I believe). So either specify the datatype (eg, `dtype=uint8' keyword in `np.ones`) or store the image using another format (e.g. NRRD).

That said, be aware that TIFF format does not store geometric information (i.e. rotation, origin, pixelspacing), and is therefore inferior to formats like NIFTII or NRRD. If you have TIFF images derived from DICOM and have access to the original DICOMS, please consider using another format. Especially features like shape features rely on correct geometric info.
