### ISSUE TITLE
[FEAT EXTRACTION] using LOG filter Image operation for feature extraction.

### ISSUE THREAD

**Issue by sneh-debug** [AIM-Harvard/pyradiomics#677]
these are my extraction parameters:
Extraction parameters:
         {'minimumROIDimensions': 2, 'minimumROISize': None, 'normalize': False, 'normalizeScale': 1, 'removeOutliers': None, 'resampledPixelSpacing': None, 'interpolator': 3, 'preCrop': False, 'padDistance': 5, 'distances': [1], 'force2D': False, 'force2Ddimension': 0, 'resegmentRange': None, 'label': 1, 'additionalInfo': True, 'binWidth': 25, 'sigma': [2], 'verbose': True}
Enabled input images:
        Wavelet
Enabled features:
         {'firstorder': [], 'glcm': [], 'gldm': [], 'glrlm': [], 'glszm': [], 'ngtdm': [], 'shape': []} 
`imageName = flair_path
            maskName = seg_path

            image = sitk.ReadImage(imageName)
            stats = sitk.LabelShapeStatisticsImageFilter()
            mask = mask = sitk.ReadImage(maskName)
            stats.Execute(mask)

            glcmFeatures = glcm.RadiomicsGLCM(image, mask, **settings)
            glcmFeatures.enableAllFeatures()

            for f in glcmFeatures.enabledFeatures.keys():
                print('  ', f)
                print(getattr(glcmFeatures, 'get%sFeatureValue' % f).__doc__)

            print('Will calculate the following GLCM features: ')
            resultsglcm = glcmFeatures.execute()`

all the feature values for LOG filter Image operation and Original Image operation are same. even for pywavelet image image operation. why it is so? am i missing somthing??

**Comment by JoostJM** [comment]
Please use the official interface of PyRadiomics (through the `featureextractor` module). You are using feature classes directly, which is only intended for deep-level development. The options you describe are not implemented at the feature class level, but in the `featureextractor`.
