### ISSUE TITLE
How to extract features from GLRLM using PyRadiomix library for a .jpg image

### ISSUE THREAD

**Issue by sk-mohiuddin** [AIM-Harvard/pyradiomics#678]
I am unable to extract GLRLM features using the PyRadiomix library for a .jpg file. It has a mask input, which is not clear to me.

I have used below code

`import SimpleITK as sitk`
`from radiomics import glrlm`
`from radiomics import featureextractor`
`image = sitk.ReadImage('D:\Desert.jpg', sitk.sitkInt8)`
`extractor = featureextractor.RadiomicsFeatureExtractor()`
`extractor.disableAllFeatures()`
`extractor.enableFeatureClassByName('glrlm')`
`result = extractor.execute(image, ******)`

What will be the 'maskFilepath' input at the last line as a second argument of the execute method?

**Comment by yuandongbo123** [comment]
you can transpose the .jpg to nii.gz

**Comment by JoostJM** [comment]
Be aware that .jpg has no geometrical information (like pixel spacing). This may result in incorrect values for certain features (especially shape features).
