### ISSUE TITLE
[FEAT EXTRACTION] Voxel based takes several hours on CT

### ISSUE THREAD

**Issue by Alsurayhi** [AIM-Harvard/pyradiomics#679]
I'm running voxel based feature extraction on lung CT. It took  6 to 7 hours to produce a result for one case and one feature. I know that voxel based would be slower than calculating a feature for the entire ROI.
 But, is the voxel based takes that long, or I'm doing some thing wrong?! Is there any way to speed up the process? 

Appreciate your help

Here is the setting info 
 
**PyRadiomics configuration**
imageType:
  Original: {}

featureClass:
  glcm:
    - 'Autocorrelation'

setting:

  binWidth: 25
 voxelArrayShift: 1000 
  label: 1

 interpolator: 'sitkBSpline'
  resampledPixelSpacing: [1, 1, 1]
  

voxelSetting:
  kernelRadius: 2
  maskedKernel: true
  initValue: nan
  voxelBatch: 5000

**Version (please complete the following information):**
 - OS: Windows 10 (16GB RAM)
 - Python version: [e.g. 3.6]
 - PyRadiomics version [ 3.7.9]

**Additional context** (RESULT)
Starting voxel based extraction
Calculating features with label: 1
Loading image and mask
Active features:
Autocorrelation

    **1. Autocorrelation**

    .. math::
      \textit{autocorrelation} = \displaystyle\sum^{N_g}_{i=1}\displaystyle\sum^{N_g}_{j=1}{p(i,j)ij}

    Autocorrelation is a measure of the magnitude of the fineness and coarseness of texture.
    
Calculating features
**Applying resampling from spacing [0.69140625 0.69140625 0.5       ] and size [512 512 689] to spacing [1. 1. 1.] and size [315, 236, 308]**
Adding image type "Original" with custom settings: {}
Calculating features for original image
Computing glcm
batch: 100%|███████████████████████████████████████████████████████████████████| 1296/1296.0 [5:19:30<00:00, 14.79s/it]
diagnostics_Versions_PyRadiomics: v3.0.1
diagnostics_Versions_Numpy: 1.19.5
diagnostics_Versions_SimpleITK: 2.0.2
diagnostics_Versions_PyWavelet: 1.1.1
diagnostics_Versions_Python: 3.7.9
diagnostics_Configuration_Settings: {'minimumROIDimensions': 2, 'minimumROISize': None, 'normalize': False, 'normalizeScale': 1, 'removeOutliers': None, 'resampledPixelSpacing': [1, 1, 1], 'interpolator': 'sitkBSpline', 'preCrop': False, 'padDistance': 10, 'distances': [1], 'force2D': False, 'force2Ddimension': 0, 'resegmentRange': None, 'label': 1, 'additionalInfo': True, 'binWidth': 25, 'voxelArrayShift': 1000, 'kernelRadius': 2, 'maskedKernel': True, 'initValue': 'nan', 'voxelBatch': 5000, 'voxelBased': True}
diagnostics_Configuration_EnabledImageTypes: {'Original': {}}
diagnostics_Image-original_Hash: 65cf193e9e0c261d771a8f9b1b23615464d6b561
diagnostics_Image-original_Dimensionality: 3D
diagnostics_Image-original_Spacing: (0.69140625, 0.69140625, 0.5)
diagnostics_Image-original_Size: (512, 512, 689)
diagnostics_Image-original_Mean: -515.6508867349611
diagnostics_Image-original_Minimum: -1024.0
diagnostics_Image-original_Maximum: 2498.0
diagnostics_Mask-original_Hash: 62680f651f099b8ffcad439bfc90ea6202424f3c
diagnostics_Mask-original_Spacing: (0.69140625, 0.69140625, 0.5)
diagnostics_Mask-original_Size: (512, 512, 689)
diagnostics_Mask-original_BoundingBox: (52, 154, 95, 423, 310, 591)
diagnostics_Mask-original_VoxelNum: 27102160
diagnostics_Mask-original_VolumeNum: 1
diagnostics_Mask-original_CenterOfMassIndex: (241.1406673121257, 307.38631957748015, 397.26735872712726)
diagnostics_Mask-original_CenterOfMass: (-41.92813236622561, -185.62547435463287, -93.36632063643637)
diagnostics_Image-interpolated_Spacing: (1.0, 1.0, 1.0)
diagnostics_Image-interpolated_Size: (315, 236, 308)
diagnostics_Image-interpolated_Mean: -338.7666917794339
diagnostics_Image-interpolated_Minimum: -1150.0
diagnostics_Image-interpolated_Maximum: 2201.0
diagnostics_Mask-interpolated_Spacing: (1.0, 1.0, 1.0)
diagnostics_Mask-interpolated_Size: (315, 236, 308)
diagnostics_Mask-interpolated_BoundingBox: (11, 11, 10, 292, 214, 296)
diagnostics_Mask-interpolated_VoxelNum: 6478901
diagnostics_Mask-interpolated_VolumeNum: 3
diagnostics_Mask-interpolated_CenterOfMassIndex: (141.55692686151556, 116.38048860447165, 161.12621446137237)
diagnostics_Mask-interpolated_CenterOfMass: (-41.943073138484436, -185.61951139552835, -93.62378553862763)
diagnostics_Mask-interpolated_Mean: -847.5820352865401
diagnostics_Mask-interpolated_Minimum: -1148.0
diagnostics_Mask-interpolated_Maximum: 444.0
Computed original_glcm_Autocorrelation, stored as "lungN_original_glcm_Autocorrelation.nrrd"

**Comment by JoostJM** [comment]
I don't find it that terribly suprising as there are 6,478,901 matrices to compute and process.
