### ISSUE TITLE
RadiomicsFeatureExtractor and getFeatureClassNames [BUG]

### ISSUE THREAD

**Issue by Pablomfm** [AIM-Harvard/pyradiomics#680]
I can import 'RadiomicsFeatureExtractor' and I can instantiating it but later I have a bug calling getFeatureClassNames, 'RadiomicsFeatureExtractor object has no attribute getFeatureClassNames'. Does anybody now how to fix that?.

Thank you very much!.

Regards.

**Comment by JoostJM** [comment]
[Already in version 1.1.0](https://pyradiomics.readthedocs.io/en/latest/changes.html#id218), this function has been moved to the global radiomics namespace. 

you can import the function by adding `from radiomics import getFeatureClasses`

**Comment by Pablomfm** [comment]
Thank you very much for your answer Joost. I really appreciate. The bug is now fixed!. I also would like to ask you if there were changes in "enableFeaturesByName".

Thank you again!

Pablo.

**Comment by JoostJM** [comment]
No, that function is still the same.
