### ISSUE TITLE
Dealing with negative gray values for feature extraction

### ISSUE THREAD

**Issue by Nicc993** [AIM-Harvard/pyradiomics#682]
Hi,
I have a problem of understanding in matrix calculation when there are negative gray values in the image. 
After z-standardization there are negative gray values in my MR images. I don't understand how pyradiomics is calculating all the matrices from this. For example, in a Gray Level Size Zone Matrix (GLSZM) P(i,j) the (i,j) - th element is equal to the number of connecting zones with gray level i and size j that occur in the ROI. i can't be negative, so negative gray values are not considered, or do they? If not, how can I fix it?

**Version:**
 - OS: Windows 10
 - Python version: 3.7.9
 - PyRadiomics version v3.0.post5+gf06ac1d

**Comment by JoostJM** [comment]
Prior to matrix calculation, there is a gray value discretization step. This step ensures that there are no negative gray values in the ROI, the minimum discretized gray value will always be 1.

**Comment by Nicc993** [comment]
ok great thanks. I was not sure about that
