### ISSUE TITLE
[FEAT EXTRACTION] Hi there, I downloaded Pyradiomics and run the examples available in the file. However, when I want to upload my new file .nrrd, the thing did not work. Can you help me please ? OS: Window 10 ; Python version:3.6; Pyradiomics version: 3.0.1

### ISSUE THREAD

**Issue by trangphan046** [AIM-Harvard/pyradiomics#684]
**Describe the bug**
A clear and concise question regarding your extraction. Please check [FAQ section](https://pyradiomics.readthedocs.io/en/latest/faq.html), PyRadiomics issues and [PyRadiomics Slicer Discourse](https://discourse.slicer.org/c/community/radiomics/23) to check if your question has been encountered before. If so, but you still require additional help, please reference related issues.

**PyRadiomics configuration**
Add any customization you applied here (i.e. the content of the parameter file used)

**PyRadiomics log file**
If available, add section of the PyRadiomics log related to your question. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**

**Version (please complete the following information):**
 - Python version: [e.g. 3.6]
 - PyRadiomics version [e.g. 2.2.0]

**Additional context**
Add any other context about your question here.

**Comment by JoostJM** [comment]
Please specify "did not work". What does not work? Do you have the log file?

Please review the template above and provide the additional information so we may be able to help you.
