### ISSUE TITLE
ModuleNotFoundError: No module named 'radiomics.featureextractor'[BUG]

### ISSUE THREAD

**Issue by Zhengym-hub** [AIM-Harvard/pyradiomics#685]
Hello Sir：
  when I run my code ,the error of ModuleNotFoundError: No module named 'radiomics.featureextractor' occured,but the day before yesterday it was ok. I  installed pyradiomics again，it still reported this error. I do not know how to solve it, can you help me? Thank you very much!
 
This is the specific error：
Traceback (most recent call last):
  File "/home/zhengym/Pycharm_Uterus/Radio_mics/AllPerson_3D/data/2 feature.py", line 6, in <module>
    import radiomics.featureextractor as FEE
ModuleNotFoundError: No module named 'radiomics.featureextractor'

Process finished with exit code 1

**Comment by JoostJM** [comment]
Can you import module `radiomics`? Please review your installed packages. There is another radiomics package which is imported as `radiomics`. If this is installed it may cause your python to be unable to find the correct `radiomics` module and its submodules.

**Comment by Zhengym-hub** [comment]
Thank you sir , according to your suggestion , I deleted radiomics packages, it works again . Thanks again !

**Comment by Zhengym-hub** [comment]
> Can you import module `radiomics`? Please review your installed packages. There is another radiomics package which is imported as `radiomics`. If this is installed it may cause your python to be unable to find the correct `radiomics` module and its submodules.
Thank you sir , according to your suggestion , I deleted radiomics packages, it works again . Thanks again !
