### ISSUE TITLE
[FEAT EXTRACTION]

### ISSUE THREAD

**Issue by gnketiah** [AIM-Harvard/pyradiomics#691]
I have calculated texture feature maps from the whole prostate using the following settings: ['kernelRadius'] = 2; ['maskedKernel'] = True; ['force2D'] = False; ['correctMask'] = True
I then intend extract or take feature (i.e. voxel) values of regions-of-interest (ROIs) drawn by radiologist for a classification task.  
1.	I would like to ask if I need to erode the ROIs by 2 pixels?  In MATLAB when I calculate whole prostate feature map using a sliding window of say 5x5 (kernel radius 2), I usually erode ROIs taken from the feature map to ensure that only voxels within the ROI contributed to the feature computation. If possible I would prefer not to erode the ROIs since there will be fewer voxels left for analysis.
2.	Secondly, I calculated voxel-based features locally or directly from the ROIs  using the same settings and compared them to those extracted from whole prostate feature map, they were different. Could you give me more insight into this? 
I would prefer the former approach for my analysis because I intend to sample feature values from multiple ROIs or randomly form the prostate.

**Comment by JoostJM** [comment]
ad 1.) No, specifying `maskedKernel = True` tells PyRadiomics to only use voxels that are both within your kernel AND withing the original ROI

ad 2.) 
>  I calculated voxel-based features locally or directly from the ROIs
Do you mean you calculated them for the separate ROIs? The difference may be due to the use of a masked kernel (see 1.)

**Comment by gnketiah** [comment]
Thanks
