### ISSUE TITLE
[FEAT EXTRACTION] Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by arpitadu** [AIM-Harvard/pyradiomics#693]
I am extracting voxel-wise features from MRI (.nii format) scans using PyRadiomics (in python). Getting the error "Segmentation fault (core dumped)", when PyRadiomics is computing GLCM features for Wavelet Image.
I have data for 50+ patients, so I tried to run on multiple patients. But, I am getting the same error for them.

Please advise.
Thanks in advance!

**PyRadiomics configuration**
Here is my Parameter file:
******************************************
imageType:
    Original: {}
    LoG: {'sigma' : [1.0, 3.0, 5.0]} 
    Wavelet:
        binWidth: 10
    Gradient:
           gradientUseSpacing: true
    LBP3D:
       lbp3DLevels: 2
       lbp3DIcosphereRadius: 2
       lbp3DIcosphereSubdivision: 1

featureClass:
    glcm: # Disable SumAverage by specifying all other GLCM features available
     - 'Autocorrelation'
     - 'JointAverage'
     - 'ClusterProminence'
     - 'ClusterShade'
     - 'ClusterTendency'
     - 'Contrast'
     - 'Correlation'
     - 'DifferenceAverage'
     - 'DifferenceEntropy'
     - 'DifferenceVariance'
     - 'JointEnergy'
     - 'JointEntropy'
     - 'Imc1'
     - 'Imc2'
     - 'Idm'
     - 'Idmn'
     - 'Id'
     - 'Idn'
     - 'InverseVariance'
     - 'MaximumProbability'
     - 'SumEntropy'
     - 'SumSquares'
    glrlm:
    glszm:
    gldm:
    #ngtdm:
    firstorder:
    shape:

setting:
    binWidth: 25 
    padDistance: 4
    preCrop: true
    label: 255
    
    
voxelSetting:
    kernelRadius: 4
    maskedKernel: true
    initValue: nan
    voxelBatch: 10000
********************************

**PyRadiomics log file**
![image](https://user-images.githubusercontent.com/42901276/115632566-20f24880-a35c-11eb-9029-fec37b3284b3.png)

**Version (please complete the following information):**
 - OS: Linux
 - Python version: 3.9
 - PyRadiomics version 

**Additional context**
It's taking a long time to process a single image, around ~5hr or more. Generally, I am getting this error after 4 hrs of the run. 
Please let me know is there any way to improve.

**Comment by JoostJM** [comment]
Sorry for the late reply. Does this happen for each image? Does it also happen if you process the case as a single image (i.e. without a csv file as input)?

If so, can you share an image and mask (anonymized) for me to debug with?

**Comment by JoostJM** [comment]
likely releated to #737
