### ISSUE TITLE
[FEAT EXTRACTION]: glrm & glcm only return 1 value instead of 14 (13 directions + mean)

### ISSUE THREAD

**Issue by LHuysmans** [AIM-Harvard/pyradiomics#694]
**Describe the bug**
When calculating the radiomics features, I expect to get multiple values for the glrm and glcm features as they are directional dependent (13 directions + mean). When I run the code below, I don't get any errors but the glrm and glcm features only contain 1 value instead of 14 (or 13?). What am I doing wrong? 

**PyRadiomics configuration**
setting:
  binWidth: 13
  label: 1
  normalize: True
  interpolator: 'sitkBSpline' 
  resampledPixelSpacing: 
  weightingNorm: 

imageType:
  Original: {} 

featureClass:
  shape:
  firstorder:
  glcm: 
  ngtdm:
  glrlm:
  glszm:
  gldm: 

**To Reproduce**
`from radiomics import featureextractor`
`image_file_path = ...`
`segm_file_path = ...`
`extractor = featureextractor.RadiomicsFeatureExtractor(param_file)`
`result = extractor.execute(image_file_path, segm_file_path)`

**Version (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.6.13
 - PyRadiomics version: 3.0.1
 - numpy version: 1.19.5
 - numpy-base version: 1.16.6

**Comment by JoostJM** [comment]
The values are averaged across directions.

**Comment by JoostJM** [comment]
see #735
