### ISSUE TITLE
4D Casting Error

### ISSUE THREAD

**Issue by salimkanoun** [AIM-Harvard/pyradiomics#697]
Hi,

We are using pyRadiomics latest version, with python 3.7.
We hit an issue for 4D mask as pyradiomics should support it with the channel selector parameter.

For all the 4D images we have a casting error being raised at radiomics calculation : 

RuntimeError: Exception thrown in SimpleITK Cast: D:\a\1\sitk\Code\BasicFilters\src\sitkCastImageFilter.cxx:95:
sitk::ERROR: Filter does not support casting from casting 32-bit unsigned integer to 32-bit unsigned integer

This is pretty curious as the error is raised when trying to cast data of the same format ? 

Here are the Nifti sample used to reproduce the isse
http://163.172.169.15/nextcloud/index.php/s/mLpAdb4qA8scgcm
http://163.172.169.15/nextcloud/index.php/s/Nz3Ta8BWcxE2XtX

For all other images in 3D we do not have any problem, this issue seems to be specific to 4D datasets.

Best regards,

Salim

**Comment by JoaoSantinha** [comment]
Hi Salim,

I think this happens because SimpleITK does not support casting of 4D images (https://discourse.itk.org/t/simpleitk-cast-4d-image/3638). 

Nonetheless, it may be useful to had a check on the input dimensions so a more clear error message can be provided in this situations.

Best regards,
Joao

**Comment by salimkanoun** [comment]
Yeah I understand but why does the casting occurs ? I have an 32-bit unsigned integer which seeems to be what pyRadiomics wants

Isn't there a bug ? 

Salim

**Comment by JoostJM** [comment]
No, that is because PyRadiomics force-casts the mask to unsigned integer. I'll take a look to see if I can fix this.

**Comment by JoostJM** [comment]
@salimkanoun, Can you also post a bit of the PyRadiomics log as well?

**Comment by salimkanoun** [comment]
Yeah here it is

`Traceback (most recent call last):
  File "C:\Users\Nicolas\Desktop\test4.py", line 18, in <module>
    results=extractor.execute(image,mask,label_channel=4)
  File "C:\Users\Nicolas\AppData\Local\Programs\Python\Python39\lib\site-packages\radiomics\featureextractor.py", line 272, in execute
    image, mask = self.loadImage(imageFilepath, maskFilepath, generalInfo, _settings)
  File "C:\Users\Nicolas\AppData\Local\Programs\Python\Python39\lib\site-packages\radiomics\featureextractor.py", line 385, in loadImage
    mask = imageoperations.getMask(mask, kwargs)
  File "C:\Users\Nicolas\AppData\Local\Programs\Python\Python39\lib\site-packages\radiomics\imageoperations.py", line 45, in getMask
    mask = sitk.Cast(mask, sitk.sitkUInt32)
  File "C:\Users\Nicolas\AppData\Local\Programs\Python\Python39\lib\site-packages\SimpleITK\SimpleITK.py", line 6323, in Cast
    return _SimpleITK.Cast(image, pixelID)
RuntimeError: Exception thrown in SimpleITK Cast: D:\a\1\sitk\Code\BasicFilters\src\sitkCastImageFilter.cxx:95:
sitk::ERROR: Filter does not support casting from casting 8-bit unsigned integer to 32-bit unsigned integer`

**Comment by JoostJM** [comment]
Never mind, I found the bug, though fixing it will require a bit more time.

PyRadiomics normally circumvents the issue of trying to resample a 4D image, as it first selects the 3D mask using the `label_channel` if it detects a 4D image.

This resultant mask is then force-cast to UInt32.

The problem in your case however, is that it did not recognize the mask as a 3D volume with a vector pixel type, but as a truly 4D volume (with spacing = 1 in the mask-channel dimension).

**Comment by JoostJM** [comment]
How did you generate the Niftii's? Is it possible to retry using nrrd?

**Comment by salimkanoun** [comment]
OK I see, in that case we might change how we generate the Nifti.

The nifti are created with our custom code using SITK. (the projet is https://github.com/salimkanoun/Dicom-To-CNN)

Is there a standard for 4D images ? 
What do you believe better, update the way we generate the nifti to get a vector pixel type ? or wait until pyradiomics can handle 4D datasets ?

**Comment by JoostJM** [comment]
@salimkanoun, My strong advice would be to use a vector pixel type. PyRadiomics *can* already handle the "4D" masks, so long as 3 of the dimensions have a spacing and match the volume input.

the 4th dimension does not have a size (mask at index 0 is not 1 mm away from mask at index 1 (along the imaginary 4th dimension)). This is what is currently suggested by your volume. What you actually want is a 3D volume, but where each pixel has multiple values, which is represented by the 3D volume with a vector pixel type.

Truly 4D volumes should be reserved for cases where there is a scale. An example is a 4D DWI, where the dimension size of the 4th dimension is the b-value. Or a dynamic contrast enhanced volume, where the size of the 4th dimension is the time since injection. None of these would apply to a mask.

**Comment by JoostJM** [comment]
While it is possible to update PyRadiomics to treat 4D masks like yours as 3D images with vector pixel types, converting them may cuase future issues (i.e. which dimension represents the vector or 4th dimension? In your case it is the last dimension, but what prevents another program from using the first dimension?). There is no information in the mask that explicitly defines the vectordimension. 

One could use the spacing or size and try to match it to the volume, but this will fail horribly if the mask is generated in another geometric space (often happens with 1 mask used to analyze multiple MRI sequences from the same study).

**Comment by salimkanoun** [comment]
Thanks for explanation ! I agree with you, we wrongly use the 4th dimenension. 

Do you have a sample code or a documentation on how we can reassign our 4th dimension in a vector pixel type ? 
we didn't work yet with vector pixel type

**Comment by JoostJM** [comment]
Refs: 

- [ExtractImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ExtractImageFilter.html#af3c522ffc6b88628a2778caf9c7d48e1)
- [ComposeImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ComposeImageFilter.html)

```
import SimpleITK as sitk
ma = sitk.ReadImage('path/to/mask.nii')

extractor = sitk.ExtractImageFilter()

ma_size = list(ma.GetSize())
ma_size[-1] = 0  # Setting the size to 0 collapses this dimension
ma_start = [0] * len(ma_size)  # extract the entire image, starting at [0, 0, 0, ...]

extractor.SetSize(tuple(ma_size))

masks = []
for ma_idx in range(ma.GetSize()[-1]):
  ma_start[-1] = ma_idx
  extractor.SetIndex(tuple(ma_start))
  masks.append(extractor.Execute(ma))

composer = sitk.ComposeImageFilter()
new_ma = composer.Execute(masks)

```

**Comment by salimkanoun** [comment]
Thanks @JoostJM  ! It's working !
Hopefully in some weeks we will get something working for the RestApi of Pyradiomics
