### ISSUE TITLE
[FEAT EXTRACTION] voxel-based extraction, resampling, and kernel size

### ISSUE THREAD

**Issue by erin5116** [AIM-Harvard/pyradiomics#699]
**Describe the bug**
I am currently extracting feature maps by enabling the voxel-based function. As my dataset have varied voxel sizes, I am using pyradiomics to resample to an isotropic voxel for the feature extraction. 
So now, when setting the kernel size, which voxel size is it based on? 
This may be a trivial question, but I couldn't see anything in the wiki that clarifies this.
Intuitively, I'd think that it is based on the resampled size..but need to confirm!

**PyRadiomics configuration**
imageType:
  Original: {}

featureClass:
  glcm:
  glrlm:
  gldm:
  ngtdm:

setting:
  resampledPixelSpacing: [0.8,0.8,0.8]
  normalize: True
  normalizeScale: 100
  removeOutliers: 3
  binWidth: 20
  force2D: True
  label: 1

voxelSetting:
  kernelRadius: 3
  maskedKernel: True
  initValue: nan
  voxelBatch: 10000

**Version (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.7.6
 - PyRadiomics version 3.0.1

**Comment by JoostJM** [comment]
Indeed it is based on the resampled voxel size. The output feature maps are also in the geometric space defined by your resampling settings.

Resampling happens prior to any feature extraction. As far as the feature classes are concerned, your resampled image and mask are the data that is provided. They have no knowledge of the original input.
