### ISSUE TITLE
Feature extraction from the whole dataset which contains DICOM files 

### ISSUE THREAD

**Issue by DrraBL** [AIM-Harvard/pyradiomics#701]
Hi,

First of all thank you for your huge work. I am new in medical filed and my actual task is to extract the features from prostateX dataset using pyradiomics  tools. I tried to reproduce the same example in the video using brain sample. the result saved in dictionary. So if I want to save the result in CVS of Json file, should I use batch model via comman line ?  because my aim is to use the features extracted to classify the data later. As i said you above that I am using dataset for prostate which  contains dicom files, my questions here are:
How can I use pyradiomics to extract feature from dicom files?
How can I extract the features across all the dataset?
could I save the output in csv file or json on google colab server?

**Version**
 - OS: Google Colab
 - Python version: 3.7
 - PyRadiomics: version 3.0.1
 - SimpleITK: 2.0.2  

Looking forward hearing from you soon
King regards,

**Comment by SyedaFatima123** [comment]
Hi . did you find any solution to your question , I have the same issue .

**Comment by DrraBL** [comment]
@SyedaFatima123 
Yes, I Have converted the whole dataset also the labels to nrrd format and then i wrote script to loop into the dataset (train sample and their labels ) which read the nrrd files and extract the features from the couple image, label.

**Comment by JoostJM** [comment]
As soon as you've converted your dataset to something like nrrd, you can use the command line interface of PyRadiomcis. It's a bit quicker as it also implements (optional) multiprocessing.
