### ISSUE TITLE
[FEAT EXTRACTION] Image original Spacing and Mask-original_Spacing

### ISSUE THREAD

**Issue by Amisnapat** [AIM-Harvard/pyradiomics#702]
Hi,
    If the image spacing and mask spacing are different (ROI mask come from CT non-contrast image but want to extract feature from CT with contrast image) 
    diagnostics_Image-original_Spacing = (0.587891, 0.587891, 3.75), size = (512, 512, 88)
    diagnostics_Mask-original_Spacing = (0.9589840000000001, 0.9589840000000001, 3.75), size = (512, 512, 88)

   Is the feature extraction value correct? In param, I already resampled the space of the image and mask to (0.5, 0.5, 0.5). 
   Or the solution is to segment again with the same size and spacing of image and mask? 

               Thank you.

**Comment by JoostJM** [comment]
If the origin and spacing are in the image formats you are using (DICOM, nrrd, niftii), the yes, the feature extraction is correct.
PyRadiomics checks if the phyisical areas of the image and mask align. If resampling is enabled, the resampling grid is based on the mask and applied to the image, ensure the same area is obtained. If no resampling is enabled, the mask can be resampled to the image space by enabling `correctMask`. This is not enabled by default to ensure researchers realize what is happening.
