### ISSUE TITLE
[FEAT EXTRACTION] Hi everyone, previously, I used the segmentation from LifeX and then apply for Pyradiomics ( file mask.nii). Now, I am wondering if I can do the segmentation directly from Pyradiomics. Thanks for your consideration.  OS: Window 10 ; Python version:3.6; Pyradiomics version: 3.0.1

### ISSUE THREAD

**Issue by trangphan046** [AIM-Harvard/pyradiomics#703]
**Describe the bug**
A clear and concise question regarding your extraction. Please check [FAQ section](https://pyradiomics.readthedocs.io/en/latest/faq.html), PyRadiomics issues and [PyRadiomics Slicer Discourse](https://discourse.slicer.org/c/community/radiomics/23) to check if your question has been encountered before. If so, but you still require additional help, please reference related issues.

**PyRadiomics configuration**
Add any customization you applied here (i.e. the content of the parameter file used)

**PyRadiomics log file**
If available, add section of the PyRadiomics log related to your question. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**

**Version (please complete the following information):**
 - Python version: [e.g. 3.6]
 - PyRadiomics version [e.g. 2.2.0]

**Additional context**
Add any other context about your question here.

**Comment by fedorov** [comment]
> I am wondering if I can do the segmentation directly from Pyradiomics

No, you cannot, but you can use 3D Slicer for this purpose, and pass the resulting segmentations to pyradiomics using SlicerRadiomics extension: https://www.slicer.org/.

**Comment by trangphan046** [comment]
> > I am wondering if I can do the segmentation directly from Pyradiomics
> 
> No, you cannot, but you can use 3D Slicer for this purpose, and pass the resulting segmentations to pyradiomics using SlicerRadiomics extension: https://www.slicer.org/.

Thank you so much but if I use 3D Slicer, it would be the same as LifeX, right?

**Comment by fedorov** [comment]
I have never used LifeX. I do not know.
