### ISSUE TITLE
Filters (Log, Wavelets...) applying on the enlarged ROI

### ISSUE THREAD

**Issue by chengjianhong** [AIM-Harvard/pyradiomics#705]
Hi, I have a practical problem. As the features are only calculated from ROI, to improve the efficiency we may consider applying the filters only on the enlarged ROIs rather than the whole image? 
I want to know whether the filters applied on the enlarged ROI will change the value of the radiomic feature.

**Comment by JoostJM** [comment]
@chengjianhong, this is already done so in the PyRadiomics code. When resampling an image, only the are of the ROI + additional padding (required for LoG and Wavelet filters) is resampled. If no resampling is enabled, a similar cropping is achieved by setting `preCrop` to true. The amount of padding can be customized by `padDistance`.
