### ISSUE TITLE
ROI normalization

### ISSUE THREAD

**Issue by zzhan127** [AIM-Harvard/pyradiomics#706]
Hi,

I have a quick question about normalization. I noticed that pyradiomics normalizes whole image instead of ROI region. I am wondering if there is any function that helps me to z score normalize ROI region?

Thanks!

**Comment by JoostJM** [comment]
If you use a fixed bin number, this 'normalizes' the ROI for texture features. For first-order, it is not possible to normalize just the ROI. This is also recommended not to do, as it makes the ROIs incomparable between patients and removes differences between patients that are of interest.

The hypothesis between whole-image normalization is that the range of gray values in an image with similar/identical acquisition protocol should be more or less the same regardless of the patient. This hypothesis does not hold true for the ROI inside that image, as it is the differences between ROIs which we are interested in for building radiomics models.

Several studies published on fixed bin width vs fixed bin number also show this, as well as higher feature stability and performance.
