### ISSUE TITLE
My  data is based on MRI and feature extraction is supported only by FirstOrder and some Shape features.

### ISSUE THREAD

**Issue by sugar-su** [AIM-Harvard/pyradiomics#707]
**Describe the bug**

--> 149     P_glcm = numpy.delete(P_glcm, emptyGrayLevels-1 , 1)
    150     P_glcm = numpy.delete(P_glcm, emptyGrayLevels -1, 2)
    151 

<__array_function__ internals> in delete(*args, **kwargs)

D:\anaconda\programy\lib\site-packages\numpy\lib\function_base.py in delete(arr, obj, axis)
   4404         else:
   4405             keep = ones(N, dtype=bool)
-> 4406             keep[obj,] = False
   4407 
   4408         slobj[axis] = keep

IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by JoostJM** [comment]
This looks like an old bug. What version of PyRadiomic do you use?
