### ISSUE TITLE
[FEAT EXTRACTION] Hi everyone, after extracting features, I got the value for " GLSZM_Small Area Emphasis", " GLSZM_Small Area High Gray Level Emphasis", "GLSZM_Small Area Low Gray Level Emphasis" for 2 kinds of image: PET original and coregistered PET. However, the percentage difference of those features in 2 images are extremely high ( 3500%,282%, 293%,...) So I am wondering if there is anyone handled this problem before? Can you please help me. Thank you so much OS: Window 10 ; Python version:3.6; Pyradiomics version: 3.0.1   

### ISSUE THREAD

**Issue by trangphan046** [AIM-Harvard/pyradiomics#708]
**Describe the bug**
A clear and concise question regarding your extraction. Please check [FAQ section](https://pyradiomics.readthedocs.io/en/latest/faq.html), PyRadiomics issues and [PyRadiomics Slicer Discourse](https://discourse.slicer.org/c/community/radiomics/23) to check if your question has been encountered before. If so, but you still require additional help, please reference related issues.

**PyRadiomics configuration**
Add any customization you applied here (i.e. the content of the parameter file used)

**PyRadiomics log file**
If available, add section of the PyRadiomics log related to your question. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**

**Version (please complete the following information):**
 - Python version: [e.g. 3.6]
 - PyRadiomics version [e.g. 2.2.0]

**Additional context**
Add any other context about your question here.

**Comment by JoostJM** [comment]
Please do not write your whole question in the title, but rather follow the template provided

**Comment by JoostJM** [comment]
Have you reviewed the images manually? What about first order features? are they similar?
I don't have enough information to really help you at the moment. However, finding the reason for these differences is not really debugging PyRadiomics, as the feature extraction processed correctly as far as I know. Therefore, this question is more related to research of the extracted feature values, and if there is a problem, it is more likely to stem from the co-registration process.
