### ISSUE TITLE
Parallel processing for voxel feature extraction

### ISSUE THREAD

**Issue by zndr27** [AIM-Harvard/pyradiomics#709]
I am aware that pyradiomics offers parallelization over subjects in a workflow by opening a new thread for each subject. 

But is there a way to do parallelization within a single subject for a voxel extraction? I could not find any mention of this in the documentation.

**Comment by JoostJM** [comment]
In-patient parallelization is not supported. The added complexity of the code does not outweigh the added performance benefit, especially as ext re actions are usually done in batch mode, where the gain would be 0. Still, you can define a batch size of voxels to process, which indicates how many voxels should be calculated in a batch. This is not true parallelization, but significantly reduces the number of iterations in python code, increasing the performance.
