### ISSUE TITLE
GLRLM and GLSZM features are duplicated in 2D extraction

### ISSUE THREAD

**Issue by alex-weston-13** [AIM-Harvard/pyradiomics#710]
**Describe the bug**
I'm using Python implementation to extract features from 2D MRI slices with whole liver segmented. I notice that when I enable "force2D" in the YAML file, the GLRLM and GLSZM features are exactly duplicated, even though the feature names are not the same. 

This is not an issue when I'm using 3D implementation. 

Additionally, GLRLM and GLSZM values are different (a.k.a. fixed) when I'm using 2D input images, but disabling "force2D" and "force2Ddimension"

**Duplicate the bug**
extractorYAML = "path_to.yaml"
extractor = radiomics.featureextractor.RadiomicsFeatureExtractor(extractorYAML)
image_sitk = sitk.GetImageFromArray(image) # image is a 2D numpy array
mask_sitk = sitk.GetImageFromArray(mask) # mask is a 2D numpy binary array with classes [0,1]
featureVector = extractor.execute(image_sitk, mask_sitk)
for key, value in featureVector.items():
    print('%s -- %s' % (key, value))

**Diagnostic information**
diagnostics_Versions_PyRadiomics -- v3.0.1
diagnostics_Versions_Numpy -- 1.18.5
diagnostics_Versions_SimpleITK -- 2.0.2
diagnostics_Versions_PyWavelet -- 1.1.1
diagnostics_Versions_Python -- 3.7.8
diagnostics_Configuration_Settings -- {'minimumROIDimensions': 2, 'minimumROISize': None, 'normalize': True, 'normalizeScale': 100, 'removeOutliers': None, 'resampledPixelSpacing': [1, 1], 'interpolator': 'sitkNearestNeighbor', 'preCrop': True, 'padDistance': 10, 'distances': [1], 'force2D': True, 'force2Ddimension': 0, 'resegmentRange': None, 'label': 1, 'additionalInfo': True, 'binCount': 256, 'voxelArrayShift': 300}
diagnostics_Configuration_EnabledImageTypes -- {'Original': {}}
diagnostics_Image-original_Hash -- 1f8dc0a71bf3aa3a20f84cb19dc4d7645a183ac7
diagnostics_Image-original_Dimensionality -- 2D
diagnostics_Image-original_Spacing -- (1.0, 1.0)
diagnostics_Image-original_Size -- (512, 512)
diagnostics_Image-original_Mean -- 41.73570971370763
diagnostics_Image-original_Minimum -- 0.0
diagnostics_Image-original_Maximum -- 761.1710423725691

**Returns**
original_glszm_GrayLevelNonUniformity -- 198.17525481313703
original_glszm_GrayLevelNonUniformityNormalized -- 0.014027127322560663
original_glszm_GrayLevelVariance -- 471.652671750371
original_glszm_HighGrayLevelZoneEmphasis -- 10473.379813137033
original_glszm_LargeAreaEmphasis -- 1.151684597961495
...
original_glrlm_GrayLevelNonUniformity -- 198.17525481313703
original_glrlm_GrayLevelNonUniformityNormalized -- 0.014027127322560663
original_glrlm_GrayLevelVariance -- 471.652671750371
original_glrlm_HighGrayLevelRunEmphasis -- 10473.379813137033
original_glrlm_LongRunEmphasis -- 1.151684597961495

(I'm only printing out the first 5 for space, but they are all exactly duplicated)

**Comment by JoostJM** [comment]
Hi @alex-weston-13,

This is not a bug. What happens is that your input is truly 2D (as in even in the file, your image/mask has only 2 dimensions). You can see this by the fact that `diagnostics_Image-original_Size -- (512, 512)` only has 2 values.

Because of this, when you enable `force2D`, what happens is that PyRadiomics extracts in 1D, cutting off the first dimension. When in 1D, there is only 1 angle, and GLRLM and GLSZM result in the same values (the size of the zone is then equal to the lenght of the run, as it is only a single consecutive line of pixels).

So in this case, just leave force2D off. It is meant for dealing with non-isotropic voxels in 3D images.

**Comment by alex-weston-13** [comment]
This makes sense! Thank you so much for the quick reply. Been puzzling over this one for a while,
Best,
Alex
