### ISSUE TITLE
Hello .  I need to extract shape features only from T2 weighted pre contrast images (coronal)with .dcm as extension and then save the result in a csv file ? Kindly help with the  code . Thank you

### ISSUE THREAD

**Issue by SyedaFatima123** [AIM-Harvard/pyradiomics#713]
**Describe the bug**
A clear and concise question regarding your extraction. Please check [FAQ section](https://pyradiomics.readthedocs.io/en/latest/faq.html), PyRadiomics issues and [PyRadiomics Slicer Discourse](https://discourse.slicer.org/c/community/radiomics/23) to check if your question has been encountered before. If so, but you still require additional help, please reference related issues.

**PyRadiomics configuration**
Add any customization you applied here (i.e. the content of the parameter file used)

**PyRadiomics log file**
If available, add section of the PyRadiomics log related to your question. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**

**Version (please complete the following information):**
 - Python version: [e.g. 3.6]
 - PyRadiomics version [e.g. 2.2.0]

**Additional context**
Add any other context about your question here.

**Comment by JoostJM** [comment]
1. Convert your DICOM files to a single-file format such as nrrd (e.g. through use of dicom2niix, plastimatch or nrrdify)
2. Create your segmentations delineating the region in the volumes from which features should be extracted
3. Create a csv file with column Image and Mask (and optional additional columns that should be copied to the output). On each row, specify the path to the image file in the image column and the path to the mask file in the mask column.
4. Run PyRadiomics from the commandline in batch mode, with optional paralellization (`--jobs`). Specify the output format as csv (`--format`).

Additional information about steps 3 and 4 can be found in the PyRadiomics documentation. As to step 1, this has been asked and answered several times in these issues. As to step 2, this is outside the scope of PyRadiomics.
