### ISSUE TITLE
How to add Wavelet Filtering in the Python Command? 

### ISSUE THREAD

**Issue by Mostafa-coder2020** [AIM-Harvard/pyradiomics#714]
Hi everyone, 

    I am trying to apply Wavelet filtering to the following command in Python: 

```
import os 

cmd='pyradiomics 1-13.dcm.nrrd Segmentation-Segment_1-label.nrrd -o test.csv -f csv'

os.system(cmd)
```

So far, I have tried to add this command instead
```
cmd='radiomics.imageoperations.getWaveletImage(1-13.dcm.nrrd, Segmentation-Segment_1-label.nrrd, **kwargs) test.csv -f csv'
```
But I got the following error:
```
sh: -c: line 0: syntax error near unexpected token `1-13.dcm.nrrd,'
sh: -c: line 0: `radiomics.imageoperations.getWaveletImage(1-13.dcm.nrrd, Segmentation-Segment_1-label.nrrd, **kwargs) test.csv -f csv'
```
I wondered what kind of command I should add to cmd in order to extract features based on Wavelet. Any help is appreciated. 

Thanks in advance.

**Comment by JoostJM** [comment]
Wavelet and other filters are  configured in the parameters file. It can also be done on the commandline, but my advise would be to use the parameters file, as it is more readable and ensures you can recreate your extraction at later time points. Usage and format are explained in the PyRadiomics documentation.

**Comment by Mostafa-coder2020** [comment]
Thanks, Joost. Yes, that is right. I have installed the Jupyter Software-https://jupyter.org/install- for using the PyRadiomics toolbox in Python instead of adding Wavelet filter into the command line. But I have a question. Is there any way to install Jypyter stand-alone on a Mac machine? It seems the Jypyter is internet-based software.

**Comment by JoostJM** [comment]
Jupyter is not internet based software, but uses your browser for visualization. Any additional questions about jupyter should be posted on a jupyter forum, as it is outside the scope of PyRadiomics.
