### ISSUE TITLE
module 'radiomics.featureextractor' has no attribute 'RadiomicsFeaturesExtractor'

### ISSUE THREAD

**Issue by Rezwanarosen** [AIM-Harvard/pyradiomics#718]
Though I installed PyRadiomics in google colab, after running the instantiating code it's showing -module 'radiomics.featureextractor' has no attribute 'RadiomicsFeaturesExtractor'. What can I do now to solve this issue?

Also, can I use .mat image files as input for feature extraction?

**Comment by JoostJM** [comment]
As to your first error. That has been a name change in version 3.0. The class inside radiomics.featureextractor is now called RadiomicsFeatureExtractor (without the s). This is to remove the difference in the name between the module and class.

I don't know what extensions .mat refers to. If it's readable by SimpleITK it should work. Be aware though that PyRadiomics also makes use of geometrical information such as origin, spacing and direction. If this information is not present in your input image (e.g. .jpg-like formats), some feature values may prove to be incorrect.

**Comment by Rezwanarosen** [comment]
Thanks!

**Comment by woaiwanyasuo** [comment]
thanks

**Comment by Madeline271** [comment]
thanks
