### ISSUE TITLE
Reading .mat file with PyRadiomics

### ISSUE THREAD

**Issue by Rezwanarosen** [AIM-Harvard/pyradiomics#720]
How can I easily read  .mat image files using pyradiomics ? Can you show me any example?

**Comment by JoostJM** [comment]
I don't know the `.mat` extension, what kind of file does this represent? PyRadiomics is able to read any file that is readable by SimpleITK.

**Comment by Rezwanarosen** [comment]
This is a file generated in Matlab and saved in .mat form

**Comment by JoostJM** [comment]
If I'm correct, that datatype only contains the array of values. That is not a format supported by PyRadiomics (geometrical information is also required). Please convert your data to file formats like NRRD or NIFTII, those should work.
