### ISSUE TITLE
RuntimeError! When i try to extract features from my datasets, there are something wrong.

### ISSUE THREAD

**Issue by cvcaiji** [AIM-Harvard/pyradiomics#722]
how shoud i fix this error?  I need help! >.<!

sitk::ERROR: Pixel type: 32-bit float is not supported in 4D by class itk::simple::NormalizeImageFilter.

**Comment by JoostJM** [comment]
PyRadiomics forces the datatype of the image to float. However, you input image is 4D and float is apparently not supported for the SimpleITK version you have installed. That said, 4D is also not supported for image input to PyRadiomics.

The solution would be to select the correct 3D volume.
