### ISSUE TITLE
Can I enable multiple features using enableFeatureClassByName or I can only do one at a time? If I provide more than one class with this function, it only runs the first provided class.[FEAT EXTRACTION]

### ISSUE THREAD

**Issue by abhinandanbatra** [AIM-Harvard/pyradiomics#726]
**Describe the bug**
A clear and concise question regarding your extraction. Please check [FAQ section](https://pyradiomics.readthedocs.io/en/latest/faq.html), PyRadiomics issues and [PyRadiomics Slicer Discourse](https://discourse.slicer.org/c/community/radiomics/23) to check if your question has been encountered before. If so, but you still require additional help, please reference related issues.

**PyRadiomics configuration**
Add any customization you applied here (i.e. the content of the parameter file used)

**PyRadiomics log file**
If available, add section of the PyRadiomics log related to your question. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**

**Version (please complete the following information):**
 - Python version: [e.g. 3.6]
 - PyRadiomics version [e.g. 2.2.0]

**Additional context**
Add any other context about your question here.

**Comment by JoostJM** [comment]
Make one call to the function for each class you want to enable.

Alternatively (and preferred): use a parameter file to configure your extraction.
