### ISSUE TITLE
[FEAT EXTRACTION] Voxel-based extraction work using python API

### ISSUE THREAD

**Issue by mattwarkentin** [AIM-Harvard/pyradiomics#728]
**Describe the bug**

Hi,

I am wondering why the voxel-based feature extraction is not performed based on the code below. I am able to get the feature map if I move the parameters below into a YAML file and then run from the command-line API, but wondering whether this can be achieved within a single python file.

When running the below code, only the segment based extraction is done. Is there a way to toggle `--mode voxel` when initializing and specifying the parameters in a python script (e.g. `voxelBased: True`)?

Thanks for your help.

**PyRadiomics configuration**

Configuration all done in Python, see below.

**To Reproduce**
```py
# (main.py)
from radiomics import featureextractor

params = {
  'featureClass': {
    'firstorder': ['Minimum']
  },
  'setting': {
    'binWidth': 25,
    'voxelArrayShift': 1000
  },
  'voxelSetting': {
    'kernelRadius': 2,
    'maskedKernel': True,
    'voxelBatch': 10000
  }
}
extractor = featureextractor.RadiomicsFeatureExtractor(params)

result = extractor.execute('ct.nrrd', 'mask.nrrd')
```

**Version (please complete the following information):**
 - OS: MacOS Big Sur 11.6
 - Python version: 3.7.10
 - PyRadiomics version: 3.0.1

**Comment by JoostJM** [comment]
add keyword argument voxelBased=True in `extractor.execute()`
