### ISSUE TITLE
I am trying to run getFeatureNames but I am getting error?

### ISSUE THREAD

**Issue by abhinandanbatra** [AIM-Harvard/pyradiomics#729]
**Describe the bug**

Here is the error when I run getFeatureNames()
'RadiomicsFeatureExtractor' object has no attribute 'getFeatureNames'.

**Comment by JoostJM** [comment]
Correct, it is a deprecated function no longer present in the current version of PyRadiomics (that functionality has been moved to a global function, i.e. radiomics.getFeatureClasses (which returns the feature classes, from which you can retrieve the feature names:

```
import radiomics
fc_dict = radiomics.getFeatureClasses()

f_names = {}
for cls_name, cls in fc_dict.items():
    f_names[cls_name] = cls.getFeatureNames()
```
