### ISSUE TITLE
[DOCS] Bounding Box coordinates

### ISSUE THREAD

**Issue by ivanzhovannik** [AIM-Harvard/pyradiomics#730]
@fedorov @JoostJM I tried to use the code for the bounding box calculation [checkMask](https://github.com/AIM-Harvard/pyradiomics/blob/master/radiomics/imageoperations.py#:~:text=def%20checkMask(imageNode%2C%20maskNode%2C%20**kwargs)%3A)

**Line 260** [`# LBound and UBound of the bounding box, as (L_X, U_X, L_Y, U_Y, L_Z, U_Z)`](https://github.com/AIM-Harvard/pyradiomics/blob/master/radiomics/imageoperations.py#:~:text=%23%20LBound%20and%20UBound%20of%20the%20bounding%20box%2C%20as%20(L_X%2C%20U_X%2C%20L_Y%2C%20U_Y%2C%20L_Z%2C%20U_Z))
AND
**Line  331** [`# LBound and size of the bounding box, as (L_X, L_Y, [L_Z], S_X, S_Y, [S_Z])`](https://github.com/AIM-Harvard/pyradiomics/blob/master/radiomics/imageoperations.py#:~:text=%23%20LBound%20and%20size%20of%20the%20bounding%20box%2C%20as%20(L_X%2C%20L_Y%2C%20%5BL_Z%5D%2C%20S_X%2C%20S_Y%2C%20%5BS_Z%5D))

seem like they contradict each other. Maybe the latter was taken from the older version. Could you please harmonize the comments and docscripting?

Thanks!

**Comment by JoostJM** [comment]
No, that is correct. The difference is due to the use of SimpleITK LabelStatistiscImageFilter and LabelShapeStatisticsImageFilter. They define a bounding box differently.
