### ISSUE TITLE
[FEAT EXTRACTION] Remove discretization

### ISSUE THREAD

**Issue by rgutsche** [AIM-Harvard/pyradiomics#732]
Hello is there a way to remove the discretization part? As input I would like to use an already preprocessed image with the right amount of gray-level values for the ROI. By default pyradiomics uses a bin_width of 25 but I would like to set it to None such that my gray-level values won't be changed while feature are extracted.

Thanks for your support!

**Version (please complete the following information):**
 - OS: [Mojave 10.14.6]
 - Python version: [e.g. 3.7.6]
 - PyRadiomics version [e.g. 3.0.1]

**Comment by fedorov** [comment]
I think you could set your bin width to 1 to achieve this, assuming your pixel values are integers.
