### ISSUE TITLE
[FEAT EXTRACTION]question on Using Filtering

### ISSUE THREAD

**Issue by yangwei1993** [AIM-Harvard/pyradiomics#736]
**my code**
settings = {}
settings['binWidth'] = 5
#settings['resampledPixelSpacing'] = None
settings['resampledPixelSpacing'] = [3, 3, 3]  # This is an example for defining resampling (voxels with size 3x3x3mm)
settings['interpolator'] = 'sitkBSpline'
settings['verbose'] = True
settings['minimumROIDimensions']=1
settings['normalize']=True
settings['normalizeScale']=100
settings['correctMask']=True
settings['voxelArrayShift']=300
#settings['geometryTolerance']=0.5
settings['getWaveletImage']=True
settings['sigma']=[3,5]
Wavelet: {}
extractor = featureextractor.RadiomicsFeatureExtractor(**settings)
filters = {
    "AdditiveGaussianNoise" : sitk.AdditiveGaussianNoiseImageFilter(),
    "Bilateral" : sitk.BilateralImageFilter(),
    "BinomialBlur" : sitk.BinomialBlurImageFilter(),
    "BoxMean" : sitk.BoxMeanImageFilter(),
    "BoxSigmaImageFilter" : sitk.BoxSigmaImageFilter(),
    "CurvatureFlow" : sitk.CurvatureFlowImageFilter(),
    "DiscreteGaussian" : sitk.DiscreteGaussianImageFilter(),
    "LaplacianSharpening" : sitk.LaplacianSharpeningImageFilter(),
    "Mean" : sitk.MeanImageFilter(),
    "Median" : sitk.MedianImageFilter(),
    "Normalize" : sitk.NormalizeImageFilter(),
    "RecursiveGaussian" : sitk.RecursiveGaussianImageFilter(),
    "ShotNoise" : sitk.ShotNoiseImageFilter(),
    "SmoothingRecursiveGaussian" : sitk.SmoothingRecursiveGaussianImageFilter(),
    "SpeckleNoise" : sitk.SpeckleNoiseImageFilter(),
}
# Filter
results = {}

results["baseline"] = extractor.execute(imageName, maskName)

for key, value in six.iteritems(filters):
    print ( "filtering with " + key )
    filtered_image = value.Execute(imageName)
    results[key] = extractor.execute(filtered_image, maskName)

**PyRadiomics log file**
when performing filtering with AdditiveGaussianNoise
_**TypeError: in method 'AdditiveGaussianNoiseImageFilter_Execute', argument 2 of type 'itk::simple::Image const &'**_

**Comment by JoostJM** [comment]
Filters don't work like that. In the documentation you can find details on how to work with filters in PyRadiomics.
