### ISSUE TITLE
[Documentation / Question] definition of p_x(i) and p_y(j) in GLCM

### ISSUE THREAD

**Issue by lyhyl** [AIM-Harvard/pyradiomics#739]
Current [docs](https://pyradiomics.readthedocs.io/en/latest/features.html#module-radiomics.glcm) gives the definitions:
`P(i,j)`  be the co-occurence matrix for an arbitrary δ and θ
`p(i,j)`  be the normalized co-occurence matrix
`p_x(i)=∑j=1..Ng P(i,j)` be the marginal row probabilities
`p_y(j)=∑j=1..Ng P(i,j)` be the marginal column probabilities

Should it be lower case `p` instead of `P` in definitions of `p_x` and `p_y`?
`p_x(i)=∑j=1..Ng p(i,j)` be the marginal row probabilities
`p_y(j)=∑i=1..Ng p(i,j)` be the marginal column probabilities

I also check the [code of pyradiomics](https://github.com/AIM-Harvard/pyradiomics/blob/03d23f7865f954ab61320b58e7bc4a83dc8b04fc/radiomics/glcm.py#L216-L219).
It looks like depends on normalized matrix `self.P_glcm` only.

Maybe there is a similar typo in [original paper (Appendix I, Page 9)](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=4309314).

**Comment by JoostJM** [comment]
Correct. Thanks for the contribution.
