### ISSUE TITLE
Cannot open link in "pyradiomics-master\notebooks\FeatureVisualization.ipynb"

### ISSUE THREAD

**Issue by HUIUIH** [AIM-Harvard/pyradiomics#748]
**Describe the bug**
Can not open link "http://www.spl.harvard.edu/publications/bitstream/download/5270" in  "pyradiomics- master\notebooks\FeatureVisualization.ipynb".  I would like to know where to download the latest example files.
Thanks.

![image](https://user-images.githubusercontent.com/60836258/157264175-660b9067-3590-469f-a15d-6661fdd4ea65.png)

![image](https://user-images.githubusercontent.com/60836258/157262218-0560e9a7-8882-4ada-80ab-9cb1285f38d3.png)

**Comment by pieper** [comment]
Thanks for pointing this out - for now you can get the data here: https://www.dropbox.com/s/19jlzvxxwt5zetg/tumorbase.zip?dl=0

It may be possible to get the original link working; it's being investigated.

**Comment by HUIUIH** [comment]
>
Thanks! It is very helpful.
