### ISSUE TITLE
[FEAT EXTRACTION] Will discontinuous ROIs work? 

### ISSUE THREAD

**Issue by amirzolal** [AIM-Harvard/pyradiomics#750]
Hello, this is rather a general question regarding the functioning of the algorithm. I have also posted this on slicer discourse but there was no reaction over several days. 

I have some ROIs that I use to extract image pixel intensity from images and would like to re-use these ROIs in feature detection. However, the ROIs are discontinuous (meaning that the a specific tissue is marked on different places in the scan, without there being  a connection between those tissues).

The radiomics program (at least pyradiomics) does produce a csv when using this ROI.

Will the output be anyhow affected by the discontinuity, i mean does the ROI border affect the feature recognition somehow?

Thanks in advance for the answer,

Amir

**Comment by giemmecci** [comment]
I'm not part of the pyradiomics team, but the case discussed here seems similar to yours: 

https://github.com/AIM-Harvard/pyradiomics/issues/689

**Comment by JoostJM** [comment]
@amirzolal, @giemmecci is correct.
