### ISSUE TITLE
Error in the NGTDM docs

### ISSUE THREAD

**Issue by sgdy3** [AIM-Harvard/pyradiomics#754]
I've found a littel error in the doc of NGTDM featurs. The shown example of NGTDM is like this:
$$\begin{split}\begin{array}{cccc} 
i & n_i & p_i & s_i\\ 
\hline 1 & 6 & 0.375 & 13.35\\ 
2 & 2 & 0.125 & 2.00\\ 
3 & 4 & 0.25  & 2.63\\ 
4 & 0 & 0.00  & 0.00\\ 
5 & 4 & 0.25  & 10.075
\end{array}\end{split}$$
But as formular caculated in the page below, $s_3$ should be equal to 3.03.
$s_3 = |3-12/5| + |3-18/5| + |3-20/8| + |3-5/3| = 3.03$
I've read this doc from [Neighbouring Gray Tone Difference Matrix (NGTDM) Features](https://pyradiomics.readthedocs.io/en/latest/_modules/radiomics/ngtdm.html#RadiomicsNGTDM)

PS.I'm new in github, not familiar with the proper format to submmit an issue. If there exist any inappropriate, pleas forgive my rudeness.

**Comment by JoostJM** [comment]
Thanks for the issue @sgdy3, it does look like a typo indeed. I'll take a look and push a fix.
