### ISSUE TITLE
Error Force2D mask in 3D mask

### ISSUE THREAD

**Issue by mfdezp11** [AIM-Harvard/pyradiomics#758]
Dear all,

I have been trying to calculated 2D radiomics of a 3D mask. I set force2D parameter to True but when I calculated it I got the following error. 

![Captura](https://user-images.githubusercontent.com/102722399/161015049-4803e38f-3fce-41dd-8e6d-d55b7536b6fe.PNG)

**Version :**
 - OS: Windows
 - Python version: 3.7
 - PyRadiomics version 3.0.1

If I set force2D to False I don't get any error. Any help?

Thanks

**Comment by JoostJM** [comment]
You have a 3D mask, so you are unable to comput 2D shape features. Use the `shape` class instead.
force2D does not magically make your mask 2D, it's a way of dealing with voxel anisotropy (by  removing offsets that move in between slices).
If you want the compute 2D shape features, you need to make your mask 2D (e.g. by only segmenting on a single slice, 3D image input is still allowed in this case).

**Comment by mfdezp11** [comment]
Thank you very much. I have calculated the shape features independently from the rest with force2D to False
