### ISSUE TITLE
Pyradiomics Features

### ISSUE THREAD

**Issue by e187603** [AIM-Harvard/pyradiomics#760]
Hello,

I'm Selman EREL from Ankara Yildirim Beyazit University, Ankara, Turkey. I'm pursuing my PhD in Electrical and Electronics Engineering Department. My PhD topic is Radiomics. I'm responsible to research on radiomics features defined as standard. I have seen PyRadiomics and it is rather useful. It says in pyradiomics website that approximately 1500 radiomics features can be extracted from an image by using pyradiomics. However, in documentation of it, 120 features (19+16+10+24+16+16+5+14) are described but rest is not mentioned. How can I reach the radiomics features that pyradiomics can extract approximately 1500 from a medical image?

Best Regards,

Selman EREL

**Comment by JoostJM** [comment]
When applying filters, the number of extracted features is compounded as e.g. firstorder_Mean extracted from original image is different from firstorder_Mean extracted from LoG-filtered image.
