### ISSUE TITLE
[FEAT EXTRACTION] Best way to parallelise multiple feature extractors

### ISSUE THREAD

**Issue by dorkylever** [AIM-Harvard/pyradiomics#816]
Hi  Devs, 

Is there a good way to parallelise multiple feature extractors?  I have a set of uCT scans with multiple organs labelled.

Something like the Joblib library? I would rather not use job lock files as I already parallelise this way (so I can run multiple specimens in parallel).

Let me know your opinions. 

Kind regards, 
Kyle

**Comment by JoostJM** [comment]
Parallelization is already implemented in de commandline entrypoints. This allows to run multiple extractions in parallel (parallelization on the case level). See documentation (TLDR: add parameter `--jobs <n_threads>`).

**Comment by dorkylever** [comment]
Hi Joost, 

Sorry, what I meant was playing around with the python:

extractor = featureextractor.RadiomicsFeatureExtractor()

and playing around with multiprocessing inside the extractor.  Is there no option for this? I can't find any in the docs. 

I'm using high performance computing and the library I'm using is heavily Python based, so I would rather load the pyradiomics python package than install the command line (I have to create a TCL module for it) and subprocess it.
