### ISSUE TITLE
[FEAT EXTRACTION] 

### ISSUE THREAD

**Issue by nimayousefi75** [AIM-Harvard/pyradiomics#818]
Hello,
I'm going to extract features from lungs(thoracic cavity)
my question is how can i specify this area and extract features with pyradiomics?

 - OS: 10
 - Python version: 3.9
 - PyRadiomics version :3.1

**Comment by dorkylever** [comment]
Hi Nima,

Pyradiomics is only available for python 3.7 or lower. 

Addtionally, you will need to create a mask of the thoracic cavity (there's many tools - 3DSlicer, ITK-SNAP [maybe Dirshti paint - would be my last choice]). Then specify that mask in your run. 

If you're doing it at low throughput I would recommend using the command line tools.

**Comment by nimayousefi75** [comment]
Thank you for your reply.
